package vn.unicloud.umeepay.enums;

public enum BusinessProduct {
    TOURIST, FOOD_AND_BEVERAGE, SERVICE, ECOMMERCE, EDUCATION, HEALTHY, BEAUTY, INSURANCE, TRANSPORT, FINANCE, HEALTH_CARE, ENTERTAINMENT, SUPERMARKET, OTHER
}
