package vn.unicloud.umeepay.enums;

public enum TransactionStatus {
    NONE, CREATED, WAITING, SUCCESS, CANCELED, FAIL, DISPENSE, DISPENSE_FAIL, DEPOSITED, DEPOSIT_FAILED, ACCOUNTING_FAILED, TIMEOUT, INVALID_AMOUNT
}
