server:
  port: ${SERVER_PORT:1124}

#Local MongoDB Configuration
spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:liquibase/master.xml
    default-schema: ${LIQUIBASE_SCHEMA:umeepay}
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/umeepay}
    username: ${DATABASE_USER:smarthome_dev}
    password: ${DATABASE_PASSWORD:!Q2w3e4r5t@@@@!Q2w3e4r5t}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: hikari-credit
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      minimum-idle: 3
      maximum-pool-size: 20
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
#    password: ${REDIS_PASSWORD:123}

umeepay:
  max-timestamp-diff-ms: ${MAX_TIMESTAMP_DIFF_MS:180000}
  public-key: ${UMEE_PAY_PUBLIC_KEY:MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgG2ex/aa8Km4Oy8rU5ARHkV7lGfWDGJnB1HHpU8mPaZTr8adCyM1hmXSil7r5S6GCnpChfECr1GdSckQXvgXoVVCkKXw1AGPPf9dc8XBFTho+j+YMC1Gz5xn7O7MMuof/9U+/6BbZXLVDcykMNcq3Bh4iem+J0kwpt/H36Z02VqhAgMBAAE=}
  private-key: ${UMEE_PAY_PRIVATE_KEY:MIICXQIBAAKBgG2ex/aa8Km4Oy8rU5ARHkV7lGfWDGJnB1HHpU8mPaZTr8adCyM1hmXSil7r5S6GCnpChfECr1GdSckQXvgXoVVCkKXw1AGPPf9dc8XBFTho+j+YMC1Gz5xn7O7MMuof/9U+/6BbZXLVDcykMNcq3Bh4iem+J0kwpt/H36Z02VqhAgMBAAECgYAApUjEORFlzoH6uySY2qD1A89R9T7JbZXrc2OT3cPLMP7+CnrAUFZkTyMlf/ovlfaF1dJ4Iu3payW+G2yTxX/bwLiT1INEf95hYmMH0r9TxAnMB5BOlRUiVG+RroGUCFihZiCGAbr8YvsS7aorH+XNT6xTSQhvSwxFbUgaXmTZKQJBALGXd6OhEoQiXnA69SyNWxxZ8WVd6LDs7PEwTUYjePt9SwRpMbInigdWRrFWf6lqOyZ4vAwwoAOSdjDrZQvZ7HsCQQCeBMDPyXmQfkeMHiWeYQ7MQMIFf+7F0yh0JqrCPYJvrSeSLuHkRcpRZATLqL2YtLXgPFCbmZhGkhugjQa3xrCTAkEAhfxWGlD67FAV2izRLzTS6bf+RVEtrtaCCZI8qs82ht9HyuMmyFfGbrSsDz3IgWQRjnwGvFevUiKdI1ll2iQnowJBAIkQOmaBre5Feq3xIFRGf91vdlvq4iO5yuck+wzM6a0QlrhX7hxg5OLATOCSlxIz/WZpKsos6kacSVZzvRX/Q/0CQQCB3OXoPqq18Pl8LKc61X/fzYwYfangW6m/Sw442qQepQPdfE/LJhihIH50VgtOdKFp9cp2O1s9hxU+u60OAmQk}
  prefix: ${VIETQR_PREFIX:1009}
  timeout: ${VIETQR_TIMEOUT:120}
  bin: ${VIETQR_BIN:970452}
  actualAccount: ${VIETQR_ACTUAL_ACCOUNT:35474013}
  paygate:
    access: ${PAYGATE_BASIC_AUTHEN_RAW:unicloud:unicloud}
    client-id: c95e68e4-4f7c-464b-9a6c-aa6a4a320149
    encrypt-key: 084F9E4A926D48FB17AB91CB105077F824EDDB6456477585D5505EF094DAFECD

# ===============================
# Keycloak Config
# ===============================
keycloak:
  realm: ${KEYCLOAK_REALM:umeepay}
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:https://idp-ca-dev.hcm.unicloud.ai/auth}
  ssl-required: ${KEYCLOAK_SSL_REQUIRED:external}
  resource: ${KEYCLOAK_RESOURCE:umee-pay}
  credentials:
    secret: ${KEYCLOAK_CREDENTIALS_SECRET:iHWZS8rcsMmSGyewHAYY1KvwQUr07V6I}
  use-resource-role-mappings: true
  bearer-only: true

keycloak-client:
  username: ${KEYCLOAK_CLIENT_USERNAME:admin}
  password: ${KEYCLOAK_CLIENT_PASSWORD:Aqswde123@}
