server:
  port: ${SERVER_PORT:1124}

#Local MongoDB Configuration
spring:
#  data:
#    mongodb:
#      database: ${MONGODB_DATABASE:vietqr}
#      host: ${MONGODB_HOST:127.0.0.1}
#      port: ${MONGODB_PORT:27017}
#      username: ${
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:liquibase/master.xml
    default-schema: ${LIQUIBASE_SCHEMA:vietqr}
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/vietqr}
    username: ${DATABASE_USER:smarthome_dev}
    password: ${DATABASE_PASSWORD:!Q2w3e4r5t@@@@!Q2w3e4r5t}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: hikari-credit
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      minimum-idle: 3
      maximum-pool-size: 20
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false

vietqr:
  prefix: ${VIETQR_PREFIX:100003}
  timeout: ${VIETQR_TIMEOUT:120}
  bin: ${VIETQR_BIN:970452}
  actualAccount: ${VIETQR_ACTUAL_ACCOUNT:35474013}
  paygate:
    access: ${PAYGATE_BASIC_AUTHEN_RAW:unicloud:unicloud}

soap:
  uri:
    inet: ${SOAP_URI_INET:https://api-core-staging.kienlongbank.com:8016/UATInetServiceV3/INetService.asmx}
  part-one-hard-key: ${PART_ONE_HARD_KEY:39827c0591d8465fa0289992a5d12058}
  part-two-access-key: ${PART_TWO_ACCESS_KEY:5E700084-D9C3-4817-8EFF-E557F8C03685}
  access-key: ${ACCESS_KEY:5E700084-D9C3-4817-8EFF-E557F8C03685}
  message-description: ${MESSAGE_QR_TRANSFER:Rut tien bang VietQR tai STM}
  default-stm-id: 1514TM15
  action:
    stm-withdrawal: ${STM_WITHDRAWAL:http://tempuri.org/STM_WithDrawal}

# ===============================
# Keycloak Config
# ===============================
keycloak:
  realm: ${KEYCLOAK_REALM:cms}
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:https://idp-staging.kienlongbank.co/auth}
  ssl-required: ${KEYCLOAK_SSL_REQUIRED:external}
  resource: ${KEYCLOAK_RESOURCE:cms-backend-client}
  credentials:
    secret: ${KEYCLOAK_CREDENTIALS_SECRET:4ca5eca8-0c6e-41fc-a98b-148641f0008f}
  use-resource-role-mappings: true
  bearer-only: true

keycloak-client:
  username: ${KEYCLOAK_CLIENT_USERNAME:admin}
  password: ${KEYCLOAK_CLIENT_PASSWORD:admin}

#Sunshine
sunshine:
  domain: ${DOMAIN:http://media:8080}
  security:
    use-webflux: ${USE_WEBFLUX:false}
    path-matcher:
      permit-all-path-patterns:
        - /webjars/swagger-ui/**
        - /v3/api-docs/**
        - /swagger-resources/**
        - /webjars/**
        - /swagger-ui/**
        - /swagger-ui.html
        - /null/swagger-resources/**
        - /actuator/**
        - /error404
        - /static/**
        - /css/**
        - /assets/**
        - /config/**
        - /request-transfer/**
        - /share-bills/**
    cors:
      allowed-origins: ${CORS_ORIGINS:https://cms-web-staging.kienlongbank.co,http://cms-frontend}
      allowed-methods: ${CORS_METHODS:*}
      allowed-headers: ${CORS_HEADERS:*}
    keycloak-realms:
      umee-backend:
        realm-name: ${PROFILE_REALM:umee-backend}
        auth-server-url: ${KEYCLOAK_URI:http://umee-keycloak}/auth
        client-id: ${PROFILE_CLIENT_ID:umee-backend-client}
        client-secret: ${PROFILE_CLIENT_SECRET:CM5uEyPuZLwC1uxPGxopPCmJiv5Vf5b8}
        token-uri: ${KEYCLOAK_URI:http://umee-keycloak}/auth/realms/${PROFILE_REALM:umee-backend}/protocol/openid-connect/token
        user-info-uri: ${KEYCLOAK_URI:http://umee-keycloak}/auth/realms/${PROFILE_REALM:umee-backend}/protocol/openid-connect/userinfo
        credentials:
          secret: ${PROFILE_CLIENT_SECRET:CM5uEyPuZLwC1uxPGxopPCmJiv5Vf5b8}
  clients:
    connection:
      maxIdleConnection: 10
      keepAliveDuration: 120
      connectionTimeout: 180
    internal:
      ekyc:
        uri: ${EKYC_API_URI:http://10.50.99.50:32000/ekyc}
      profile:
        uri: ${PROFILE_URI:http://10.50.99.50:32000/profile}
      smartbank:
        uri: ${SMART_BANK_URI:http://10.50.99.50:32000/smartbank}
      schedule:
        uri: ${SCHEDULE_URI:http://10.50.99.50:32000/schedule}
        properties:
          transaction_schedule_access_key: ${TRANSACTION_SCHEDULE_ACCESS_KEY:5rv5gebnmz2uhfhps939sm7wsdgse9ne}
    external:
      corebank:
        uri: ${KIENLONG_URI:https://ksbapitest.kienlongbank.com:2302/KsMobiApiDev}
        properties:
          access-key-bank: ${KIENLONG_AUTH:Basic S1NNT0JJOjFjZDlkZTM4YmM0YjI5NDM2MTg4MjAyNzNmYjU1OTk0OWQwYmJjMjk5ZTZjOTg0YmI1MTM4N2U2OTQ2NTYxYzc=}

  otp:
    timePeriod: ${OTP_PERIOD:30}
    allowedPeriodDiscrepancy: ${OTP_ALLOWED_PERIOD_DISCREPANCY:5}
    lockDuration: ${OTP_LOCK_DURATION:900}
    expiredTime: ${OTP_EXPIRED_TIME:4}

  card:
    generate-card-id-key: ${GENERATE_CARD_ID_KEY:KlbCreditCard20202020}