server:
  port: ${SERVER_PORT:1124}

#Local MongoDB Configuration
spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:liquibase/master.xml
    default-schema: ${LIQUIBASE_SCHEMA:umeepay}
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/umeepay}
    username: ${DATABASE_USER:smarthome_dev}
    password: ${DATABASE_PASSWORD:!Q2w3e4r5t@@@@!Q2w3e4r5t}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: hikari-credit
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      minimum-idle: 3
      maximum-pool-size: 20
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:123}

umeepay:
  max-timestamp-diff-ms: ${MAX_TIMESTAMP_DIFF_MS:180000}
  public-key: ${UMEE_PAY_PUBLIC_KEY:MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgG2ex/aa8Km4Oy8rU5ARHkV7lGfWDGJnB1HHpU8mPaZTr8adCyM1hmXSil7r5S6GCnpChfECr1GdSckQXvgXoVVCkKXw1AGPPf9dc8XBFTho+j+YMC1Gz5xn7O7MMuof/9U+/6BbZXLVDcykMNcq3Bh4iem+J0kwpt/H36Z02VqhAgMBAAE=}
  private-key: ${UMEE_PAY_PRIVATE_KEY:MIICXQIBAAKBgG2ex/aa8Km4Oy8rU5ARHkV7lGfWDGJnB1HHpU8mPaZTr8adCyM1hmXSil7r5S6GCnpChfECr1GdSckQXvgXoVVCkKXw1AGPPf9dc8XBFTho+j+YMC1Gz5xn7O7MMuof/9U+/6BbZXLVDcykMNcq3Bh4iem+J0kwpt/H36Z02VqhAgMBAAECgYAApUjEORFlzoH6uySY2qD1A89R9T7JbZXrc2OT3cPLMP7+CnrAUFZkTyMlf/ovlfaF1dJ4Iu3payW+G2yTxX/bwLiT1INEf95hYmMH0r9TxAnMB5BOlRUiVG+RroGUCFihZiCGAbr8YvsS7aorH+XNT6xTSQhvSwxFbUgaXmTZKQJBALGXd6OhEoQiXnA69SyNWxxZ8WVd6LDs7PEwTUYjePt9SwRpMbInigdWRrFWf6lqOyZ4vAwwoAOSdjDrZQvZ7HsCQQCeBMDPyXmQfkeMHiWeYQ7MQMIFf+7F0yh0JqrCPYJvrSeSLuHkRcpRZATLqL2YtLXgPFCbmZhGkhugjQa3xrCTAkEAhfxWGlD67FAV2izRLzTS6bf+RVEtrtaCCZI8qs82ht9HyuMmyFfGbrSsDz3IgWQRjnwGvFevUiKdI1ll2iQnowJBAIkQOmaBre5Feq3xIFRGf91vdlvq4iO5yuck+wzM6a0QlrhX7hxg5OLATOCSlxIz/WZpKsos6kacSVZzvRX/Q/0CQQCB3OXoPqq18Pl8LKc61X/fzYwYfangW6m/Sw442qQepQPdfE/LJhihIH50VgtOdKFp9cp2O1s9hxU+u60OAmQk}
  prefix: ${VIETQR_PREFIX:100003}
  timeout: ${VIETQR_TIMEOUT:120}
  bin: ${VIETQR_BIN:970452}
  actualAccount: ${VIETQR_ACTUAL_ACCOUNT:35474013}
  paygate:
    access: ${PAYGATE_BASIC_AUTHEN_RAW:unicloud:unicloud}

# ===============================
# Keycloak Config
# ===============================
keycloak:
  realm: ${KEYCLOAK_REALM:umeepay}
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:https://idp-ca-dev.hcm.unicloud.ai/auth}
  ssl-required: ${KEYCLOAK_SSL_REQUIRED:external}
  resource: ${KEYCLOAK_RESOURCE:umee-pay}
  credentials:
    secret: ${KEYCLOAK_CREDENTIALS_SECRET:KCCed5XMyObFlJPu7xWlg59mLiYThWzI}
  use-resource-role-mappings: true
  bearer-only: true

keycloak-client:
  username: ${KEYCLOAK_CLIENT_USERNAME:admin}
  password: ${KEYCLOAK_CLIENT_PASSWORD:Aqswde123@}

#Sunshine
#sunshine:
#  domain: ${DOMAIN:http://media:8080}
#  security:
#    use-webflux: ${USE_WEBFLUX:false}
#    path-matcher:
#      permit-all-path-patterns:
#        - /webjars/swagger-ui/**
#        - /v3/api-docs/**
#        - /swagger-resources/**
#        - /webjars/**
#        - /swagger-ui/**
#        - /swagger-ui.html
#        - /null/swagger-resources/**
#        - /actuator/**
#        - /error404
#        - /static/**
#        - /css/**
#        - /assets/**
#        - /config/**
#        - /request-transfer/**
#        - /share-bills/**
#    cors:
#      allowed-origins: ${CORS_ORIGINS:https://cms-web-staging.kienlongbank.co,http://cms-frontend}
#      allowed-methods: ${CORS_METHODS:*}
#      allowed-headers: ${CORS_HEADERS:*}
#    keycloak-realms:
#      umee-backend:
#        realm-name: ${PROFILE_REALM:umee-backend}
#        auth-server-url: ${KEYCLOAK_URI:http://umee-keycloak}/auth
#        client-id: ${PROFILE_CLIENT_ID:umee-backend-client}
#        client-secret: ${PROFILE_CLIENT_SECRET:CM5uEyPuZLwC1uxPGxopPCmJiv5Vf5b8}
#        token-uri: ${KEYCLOAK_URI:http://umee-keycloak}/auth/realms/${PROFILE_REALM:umee-backend}/protocol/openid-connect/token
#        user-info-uri: ${KEYCLOAK_URI:http://umee-keycloak}/auth/realms/${PROFILE_REALM:umee-backend}/protocol/openid-connect/userinfo
#        credentials:
#          secret: ${PROFILE_CLIENT_SECRET:CM5uEyPuZLwC1uxPGxopPCmJiv5Vf5b8}
#  clients:
#    connection:
#      maxIdleConnection: 10
#      keepAliveDuration: 120
#      connectionTimeout: 180
#    internal:
#      ekyc:
#        uri: ${EKYC_API_URI:http://10.50.99.50:32000/ekyc}
#      profile:
#        uri: ${PROFILE_URI:http://10.50.99.50:32000/profile}
#      smartbank:
#        uri: ${SMART_BANK_URI:http://10.50.99.50:32000/smartbank}
#      schedule:
#        uri: ${SCHEDULE_URI:http://10.50.99.50:32000/schedule}
#        properties:
#          transaction_schedule_access_key: ${TRANSACTION_SCHEDULE_ACCESS_KEY:5rv5gebnmz2uhfhps939sm7wsdgse9ne}
#    external:
#      corebank:
#        uri: ${KIENLONG_URI:https://ksbapitest.kienlongbank.com:2302/KsMobiApiDev}
#        properties:
#          access-key-bank: ${KIENLONG_AUTH:Basic S1NNT0JJOjFjZDlkZTM4YmM0YjI5NDM2MTg4MjAyNzNmYjU1OTk0OWQwYmJjMjk5ZTZjOTg0YmI1MTM4N2U2OTQ2NTYxYzc=}
#
#  otp:
#    timePeriod: ${OTP_PERIOD:30}
#    allowedPeriodDiscrepancy: ${OTP_ALLOWED_PERIOD_DISCREPANCY:5}
#    lockDuration: ${OTP_LOCK_DURATION:900}
#    expiredTime: ${OTP_EXPIRED_TIME:4}
#
#  card:
#    generate-card-id-key: ${GENERATE_CARD_ID_KEY:KlbCreditCard20202020}