//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.08 at 01:42:57 PM NOVT 
//


package vn.unicloud.vietqr.soap.inetservice.model;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="in_ck_acctnbr" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="in_ORIGPERSNBR" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="in_holdtyp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="in_holdamount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="in_effdate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="in_inactivedate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inCkAcctnbr",
    "inORIGPERSNBR",
    "inHoldtyp",
    "inHoldamount",
    "inEffdate",
    "inInactivedate"
})
@XmlRootElement(name = "AccountHold")
public class AccountHold {

    @XmlElement(name = "in_ck_acctnbr", required = true)
    protected BigDecimal inCkAcctnbr;
    @XmlElement(name = "in_ORIGPERSNBR", required = true)
    protected BigDecimal inORIGPERSNBR;
    @XmlElement(name = "in_holdtyp")
    protected String inHoldtyp;
    @XmlElement(name = "in_holdamount", required = true)
    protected BigDecimal inHoldamount;
    @XmlElement(name = "in_effdate")
    protected String inEffdate;
    @XmlElement(name = "in_inactivedate")
    protected String inInactivedate;

    /**
     * Gets the value of the inCkAcctnbr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInCkAcctnbr() {
        return inCkAcctnbr;
    }

    /**
     * Sets the value of the inCkAcctnbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInCkAcctnbr(BigDecimal value) {
        this.inCkAcctnbr = value;
    }

    /**
     * Gets the value of the inORIGPERSNBR property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInORIGPERSNBR() {
        return inORIGPERSNBR;
    }

    /**
     * Sets the value of the inORIGPERSNBR property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInORIGPERSNBR(BigDecimal value) {
        this.inORIGPERSNBR = value;
    }

    /**
     * Gets the value of the inHoldtyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInHoldtyp() {
        return inHoldtyp;
    }

    /**
     * Sets the value of the inHoldtyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInHoldtyp(String value) {
        this.inHoldtyp = value;
    }

    /**
     * Gets the value of the inHoldamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInHoldamount() {
        return inHoldamount;
    }

    /**
     * Sets the value of the inHoldamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInHoldamount(BigDecimal value) {
        this.inHoldamount = value;
    }

    /**
     * Gets the value of the inEffdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInEffdate() {
        return inEffdate;
    }

    /**
     * Sets the value of the inEffdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInEffdate(String value) {
        this.inEffdate = value;
    }

    /**
     * Gets the value of the inInactivedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInInactivedate() {
        return inInactivedate;
    }

    /**
     * Sets the value of the inInactivedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInInactivedate(String value) {
        this.inInactivedate = value;
    }

}
