//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.08 at 01:42:57 PM NOVT 
//


package vn.unicloud.vietqr.soap.inetservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AcctBankCheckSvcInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcctBankCheckSvcInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AcctBankCheckID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AcctNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BankCheckNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReferenceAcctNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExtCheckNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CheckDigitNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PayTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateLastMaint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CurrBankcheckStatCD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MenoInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcctBankCheckSvcInfo", propOrder = {
    "acctBankCheckID",
    "acctNbr",
    "bankCheckNbr",
    "referenceAcctNbr",
    "extCheckNbr",
    "checkDigitNbr",
    "payTo",
    "dateLastMaint",
    "currBankcheckStatCD",
    "menoInfo"
})
public class AcctBankCheckSvcInfo {

    @XmlElement(name = "AcctBankCheckID")
    protected String acctBankCheckID;
    @XmlElement(name = "AcctNbr")
    protected String acctNbr;
    @XmlElement(name = "BankCheckNbr")
    protected String bankCheckNbr;
    @XmlElement(name = "ReferenceAcctNbr")
    protected String referenceAcctNbr;
    @XmlElement(name = "ExtCheckNbr")
    protected String extCheckNbr;
    @XmlElement(name = "CheckDigitNbr")
    protected String checkDigitNbr;
    @XmlElement(name = "PayTo")
    protected String payTo;
    @XmlElement(name = "DateLastMaint")
    protected String dateLastMaint;
    @XmlElement(name = "CurrBankcheckStatCD")
    protected String currBankcheckStatCD;
    @XmlElement(name = "MenoInfo")
    protected String menoInfo;

    /**
     * Gets the value of the acctBankCheckID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctBankCheckID() {
        return acctBankCheckID;
    }

    /**
     * Sets the value of the acctBankCheckID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctBankCheckID(String value) {
        this.acctBankCheckID = value;
    }

    /**
     * Gets the value of the acctNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctNbr() {
        return acctNbr;
    }

    /**
     * Sets the value of the acctNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctNbr(String value) {
        this.acctNbr = value;
    }

    /**
     * Gets the value of the bankCheckNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankCheckNbr() {
        return bankCheckNbr;
    }

    /**
     * Sets the value of the bankCheckNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankCheckNbr(String value) {
        this.bankCheckNbr = value;
    }

    /**
     * Gets the value of the referenceAcctNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceAcctNbr() {
        return referenceAcctNbr;
    }

    /**
     * Sets the value of the referenceAcctNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceAcctNbr(String value) {
        this.referenceAcctNbr = value;
    }

    /**
     * Gets the value of the extCheckNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtCheckNbr() {
        return extCheckNbr;
    }

    /**
     * Sets the value of the extCheckNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtCheckNbr(String value) {
        this.extCheckNbr = value;
    }

    /**
     * Gets the value of the checkDigitNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckDigitNbr() {
        return checkDigitNbr;
    }

    /**
     * Sets the value of the checkDigitNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckDigitNbr(String value) {
        this.checkDigitNbr = value;
    }

    /**
     * Gets the value of the payTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayTo() {
        return payTo;
    }

    /**
     * Sets the value of the payTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayTo(String value) {
        this.payTo = value;
    }

    /**
     * Gets the value of the dateLastMaint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateLastMaint() {
        return dateLastMaint;
    }

    /**
     * Sets the value of the dateLastMaint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateLastMaint(String value) {
        this.dateLastMaint = value;
    }

    /**
     * Gets the value of the currBankcheckStatCD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrBankcheckStatCD() {
        return currBankcheckStatCD;
    }

    /**
     * Sets the value of the currBankcheckStatCD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrBankcheckStatCD(String value) {
        this.currBankcheckStatCD = value;
    }

    /**
     * Gets the value of the menoInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMenoInfo() {
        return menoInfo;
    }

    /**
     * Sets the value of the menoInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMenoInfo(String value) {
        this.menoInfo = value;
    }

}
