//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.08 at 01:42:57 PM NOVT 
//


package vn.unicloud.vietqr.soap.inetservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AcctBankCheckSvcInfoSrz complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcctBankCheckSvcInfoSrz">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AcctBankCheckSvcInfoItem" type="{http://tempuri.org/}ArrayOfAcctBankCheckSvcInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcctBankCheckSvcInfoSrz", propOrder = {
    "errorMessage",
    "acctBankCheckSvcInfoItem"
})
public class AcctBankCheckSvcInfoSrz {

    @XmlElement(name = "ErrorMessage")
    protected String errorMessage;
    @XmlElement(name = "AcctBankCheckSvcInfoItem")
    protected ArrayOfAcctBankCheckSvcInfo acctBankCheckSvcInfoItem;

    /**
     * Gets the value of the errorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * Sets the value of the errorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMessage(String value) {
        this.errorMessage = value;
    }

    /**
     * Gets the value of the acctBankCheckSvcInfoItem property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfAcctBankCheckSvcInfo }
     *     
     */
    public ArrayOfAcctBankCheckSvcInfo getAcctBankCheckSvcInfoItem() {
        return acctBankCheckSvcInfoItem;
    }

    /**
     * Sets the value of the acctBankCheckSvcInfoItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfAcctBankCheckSvcInfo }
     *     
     */
    public void setAcctBankCheckSvcInfoItem(ArrayOfAcctBankCheckSvcInfo value) {
        this.acctBankCheckSvcInfoItem = value;
    }

}
