//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.08 at 01:42:57 PM NOVT 
//


package vn.unicloud.vietqr.soap.inetservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BankExtInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BankExtInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ShNH" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaNH" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaCN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TenNH" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TrungGianYN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BuTruYN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaTinh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LNHYN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VCBYN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateLastMaint" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BankExtInfo", propOrder = {
    "shNH",
    "maNH",
    "maCN",
    "tenNH",
    "trungGianYN",
    "buTruYN",
    "maTinh",
    "lnhyn",
    "vcbyn",
    "dateLastMaint"
})
public class BankExtInfo {

    @XmlElement(name = "ShNH")
    protected String shNH;
    @XmlElement(name = "MaNH")
    protected String maNH;
    @XmlElement(name = "MaCN")
    protected String maCN;
    @XmlElement(name = "TenNH")
    protected String tenNH;
    @XmlElement(name = "TrungGianYN")
    protected String trungGianYN;
    @XmlElement(name = "BuTruYN")
    protected String buTruYN;
    @XmlElement(name = "MaTinh")
    protected String maTinh;
    @XmlElement(name = "LNHYN")
    protected String lnhyn;
    @XmlElement(name = "VCBYN")
    protected String vcbyn;
    @XmlElement(name = "DateLastMaint")
    protected String dateLastMaint;

    /**
     * Gets the value of the shNH property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShNH() {
        return shNH;
    }

    /**
     * Sets the value of the shNH property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShNH(String value) {
        this.shNH = value;
    }

    /**
     * Gets the value of the maNH property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaNH() {
        return maNH;
    }

    /**
     * Sets the value of the maNH property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaNH(String value) {
        this.maNH = value;
    }

    /**
     * Gets the value of the maCN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaCN() {
        return maCN;
    }

    /**
     * Sets the value of the maCN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaCN(String value) {
        this.maCN = value;
    }

    /**
     * Gets the value of the tenNH property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenNH() {
        return tenNH;
    }

    /**
     * Sets the value of the tenNH property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenNH(String value) {
        this.tenNH = value;
    }

    /**
     * Gets the value of the trungGianYN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrungGianYN() {
        return trungGianYN;
    }

    /**
     * Sets the value of the trungGianYN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrungGianYN(String value) {
        this.trungGianYN = value;
    }

    /**
     * Gets the value of the buTruYN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuTruYN() {
        return buTruYN;
    }

    /**
     * Sets the value of the buTruYN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuTruYN(String value) {
        this.buTruYN = value;
    }

    /**
     * Gets the value of the maTinh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaTinh() {
        return maTinh;
    }

    /**
     * Sets the value of the maTinh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaTinh(String value) {
        this.maTinh = value;
    }

    /**
     * Gets the value of the lnhyn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLNHYN() {
        return lnhyn;
    }

    /**
     * Sets the value of the lnhyn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLNHYN(String value) {
        this.lnhyn = value;
    }

    /**
     * Gets the value of the vcbyn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVCBYN() {
        return vcbyn;
    }

    /**
     * Sets the value of the vcbyn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVCBYN(String value) {
        this.vcbyn = value;
    }

    /**
     * Gets the value of the dateLastMaint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateLastMaint() {
        return dateLastMaint;
    }

    /**
     * Sets the value of the dateLastMaint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateLastMaint(String value) {
        this.dateLastMaint = value;
    }

}
