//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.08 at 01:42:57 PM NOVT 
//


package vn.unicloud.vietqr.soap.inetservice.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inTDAcctNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inCKAcctNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inNgaygd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inCashboxNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inOrigPersNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inApprPersNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inTDAcctNbr",
    "inCKAcctNbr",
    "inNgaygd",
    "inCashboxNbr",
    "inOrigPersNbr",
    "inApprPersNbr"
})
@XmlRootElement(name = "CreateFinalizeSavOnline")
public class CreateFinalizeSavOnline {

    protected String inTDAcctNbr;
    protected String inCKAcctNbr;
    protected String inNgaygd;
    protected String inCashboxNbr;
    protected String inOrigPersNbr;
    protected String inApprPersNbr;

    /**
     * Gets the value of the inTDAcctNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInTDAcctNbr() {
        return inTDAcctNbr;
    }

    /**
     * Sets the value of the inTDAcctNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInTDAcctNbr(String value) {
        this.inTDAcctNbr = value;
    }

    /**
     * Gets the value of the inCKAcctNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInCKAcctNbr() {
        return inCKAcctNbr;
    }

    /**
     * Sets the value of the inCKAcctNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInCKAcctNbr(String value) {
        this.inCKAcctNbr = value;
    }

    /**
     * Gets the value of the inNgaygd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInNgaygd() {
        return inNgaygd;
    }

    /**
     * Sets the value of the inNgaygd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInNgaygd(String value) {
        this.inNgaygd = value;
    }

    /**
     * Gets the value of the inCashboxNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInCashboxNbr() {
        return inCashboxNbr;
    }

    /**
     * Sets the value of the inCashboxNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInCashboxNbr(String value) {
        this.inCashboxNbr = value;
    }

    /**
     * Gets the value of the inOrigPersNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInOrigPersNbr() {
        return inOrigPersNbr;
    }

    /**
     * Sets the value of the inOrigPersNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInOrigPersNbr(String value) {
        this.inOrigPersNbr = value;
    }

    /**
     * Gets the value of the inApprPersNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInApprPersNbr() {
        return inApprPersNbr;
    }

    /**
     * Sets the value of the inApprPersNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInApprPersNbr(String value) {
        this.inApprPersNbr = value;
    }

}
