//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.08 at 01:42:57 PM NOVT 
//


package vn.unicloud.vietqr.soap.inetservice.model;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="frAcct" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="toAcct" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="costAcctNbr" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="transAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="costAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ngaygd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="intRtxnDestText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="chargeType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="trongHTYN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="payTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cmnd_NN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="telDC_NN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="soTK" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="shNH" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="internalDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nguoigui" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cmnd_NG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="telDC_NG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dueDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="transType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="frProvinceCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toProvinceCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="frBranchCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inNgayHold" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transId",
    "frAcct",
    "toAcct",
    "costAcctNbr",
    "transAmount",
    "costAmount",
    "ngaygd",
    "intRtxnDestText",
    "chargeType",
    "trongHTYN",
    "payTo",
    "cmndNN",
    "telDCNN",
    "soTK",
    "shNH",
    "internalDesc",
    "nguoigui",
    "cmndNG",
    "telDCNG",
    "dueDate",
    "transType",
    "frProvinceCode",
    "toProvinceCode",
    "frBranchCode",
    "inNgayHold"
})
@XmlRootElement(name = "CreateSchedule_ITND")
public class CreateScheduleITND {

    protected String transId;
    @XmlElement(required = true)
    protected BigDecimal frAcct;
    @XmlElement(required = true)
    protected BigDecimal toAcct;
    @XmlElement(required = true)
    protected BigDecimal costAcctNbr;
    @XmlElement(required = true)
    protected BigDecimal transAmount;
    @XmlElement(required = true)
    protected BigDecimal costAmount;
    protected String ngaygd;
    protected String intRtxnDestText;
    protected String chargeType;
    protected String trongHTYN;
    protected String payTo;
    @XmlElement(name = "cmnd_NN")
    protected String cmndNN;
    @XmlElement(name = "telDC_NN")
    protected String telDCNN;
    protected String soTK;
    protected String shNH;
    protected String internalDesc;
    protected String nguoigui;
    @XmlElement(name = "cmnd_NG")
    protected String cmndNG;
    @XmlElement(name = "telDC_NG")
    protected String telDCNG;
    protected String dueDate;
    protected String transType;
    protected String frProvinceCode;
    protected String toProvinceCode;
    protected String frBranchCode;
    protected String inNgayHold;

    /**
     * Gets the value of the transId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransId() {
        return transId;
    }

    /**
     * Sets the value of the transId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransId(String value) {
        this.transId = value;
    }

    /**
     * Gets the value of the frAcct property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFrAcct() {
        return frAcct;
    }

    /**
     * Sets the value of the frAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFrAcct(BigDecimal value) {
        this.frAcct = value;
    }

    /**
     * Gets the value of the toAcct property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getToAcct() {
        return toAcct;
    }

    /**
     * Sets the value of the toAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setToAcct(BigDecimal value) {
        this.toAcct = value;
    }

    /**
     * Gets the value of the costAcctNbr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCostAcctNbr() {
        return costAcctNbr;
    }

    /**
     * Sets the value of the costAcctNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCostAcctNbr(BigDecimal value) {
        this.costAcctNbr = value;
    }

    /**
     * Gets the value of the transAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTransAmount() {
        return transAmount;
    }

    /**
     * Sets the value of the transAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTransAmount(BigDecimal value) {
        this.transAmount = value;
    }

    /**
     * Gets the value of the costAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCostAmount() {
        return costAmount;
    }

    /**
     * Sets the value of the costAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCostAmount(BigDecimal value) {
        this.costAmount = value;
    }

    /**
     * Gets the value of the ngaygd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNgaygd() {
        return ngaygd;
    }

    /**
     * Sets the value of the ngaygd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNgaygd(String value) {
        this.ngaygd = value;
    }

    /**
     * Gets the value of the intRtxnDestText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntRtxnDestText() {
        return intRtxnDestText;
    }

    /**
     * Sets the value of the intRtxnDestText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntRtxnDestText(String value) {
        this.intRtxnDestText = value;
    }

    /**
     * Gets the value of the chargeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeType() {
        return chargeType;
    }

    /**
     * Sets the value of the chargeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeType(String value) {
        this.chargeType = value;
    }

    /**
     * Gets the value of the trongHTYN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrongHTYN() {
        return trongHTYN;
    }

    /**
     * Sets the value of the trongHTYN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrongHTYN(String value) {
        this.trongHTYN = value;
    }

    /**
     * Gets the value of the payTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayTo() {
        return payTo;
    }

    /**
     * Sets the value of the payTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayTo(String value) {
        this.payTo = value;
    }

    /**
     * Gets the value of the cmndNN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmndNN() {
        return cmndNN;
    }

    /**
     * Sets the value of the cmndNN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmndNN(String value) {
        this.cmndNN = value;
    }

    /**
     * Gets the value of the telDCNN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelDCNN() {
        return telDCNN;
    }

    /**
     * Sets the value of the telDCNN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelDCNN(String value) {
        this.telDCNN = value;
    }

    /**
     * Gets the value of the soTK property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoTK() {
        return soTK;
    }

    /**
     * Sets the value of the soTK property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoTK(String value) {
        this.soTK = value;
    }

    /**
     * Gets the value of the shNH property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShNH() {
        return shNH;
    }

    /**
     * Sets the value of the shNH property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShNH(String value) {
        this.shNH = value;
    }

    /**
     * Gets the value of the internalDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalDesc() {
        return internalDesc;
    }

    /**
     * Sets the value of the internalDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalDesc(String value) {
        this.internalDesc = value;
    }

    /**
     * Gets the value of the nguoigui property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNguoigui() {
        return nguoigui;
    }

    /**
     * Sets the value of the nguoigui property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNguoigui(String value) {
        this.nguoigui = value;
    }

    /**
     * Gets the value of the cmndNG property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCmndNG() {
        return cmndNG;
    }

    /**
     * Sets the value of the cmndNG property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCmndNG(String value) {
        this.cmndNG = value;
    }

    /**
     * Gets the value of the telDCNG property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelDCNG() {
        return telDCNG;
    }

    /**
     * Sets the value of the telDCNG property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelDCNG(String value) {
        this.telDCNG = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueDate(String value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the transType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransType() {
        return transType;
    }

    /**
     * Sets the value of the transType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransType(String value) {
        this.transType = value;
    }

    /**
     * Gets the value of the frProvinceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrProvinceCode() {
        return frProvinceCode;
    }

    /**
     * Sets the value of the frProvinceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrProvinceCode(String value) {
        this.frProvinceCode = value;
    }

    /**
     * Gets the value of the toProvinceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToProvinceCode() {
        return toProvinceCode;
    }

    /**
     * Sets the value of the toProvinceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToProvinceCode(String value) {
        this.toProvinceCode = value;
    }

    /**
     * Gets the value of the frBranchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrBranchCode() {
        return frBranchCode;
    }

    /**
     * Sets the value of the frBranchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrBranchCode(String value) {
        this.frBranchCode = value;
    }

    /**
     * Gets the value of the inNgayHold property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInNgayHold() {
        return inNgayHold;
    }

    /**
     * Sets the value of the inNgayHold property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInNgayHold(String value) {
        this.inNgayHold = value;
    }

}
