//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.08 at 01:42:57 PM NOVT 
//


package vn.unicloud.vietqr.soap.inetservice.model;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inFromAcctNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inTranAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="inNgaygd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inCashboxNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inOrigPersNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inApprPersNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IntRtxnDescText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inIsDeposit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="inPernbr" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="inMJ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inMI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isAllotment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inFromAcctNbr",
    "inTranAmount",
    "inNgaygd",
    "inCashboxNbr",
    "inOrigPersNbr",
    "inApprPersNbr",
    "intRtxnDescText",
    "inIsDeposit",
    "inPernbr",
    "inMJ",
    "inMI",
    "isAllotment"
})
@XmlRootElement(name = "CreateDepositOnline")
public class CreateDepositOnline {

    protected String inFromAcctNbr;
    @XmlElement(required = true)
    protected BigDecimal inTranAmount;
    protected String inNgaygd;
    protected String inCashboxNbr;
    protected String inOrigPersNbr;
    protected String inApprPersNbr;
    @XmlElement(name = "IntRtxnDescText")
    protected String intRtxnDescText;
    @XmlElement(required = true)
    protected BigDecimal inIsDeposit;
    @XmlElement(required = true)
    protected BigDecimal inPernbr;
    protected String inMJ;
    protected String inMI;
    protected String isAllotment;

    /**
     * Gets the value of the inFromAcctNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInFromAcctNbr() {
        return inFromAcctNbr;
    }

    /**
     * Sets the value of the inFromAcctNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInFromAcctNbr(String value) {
        this.inFromAcctNbr = value;
    }

    /**
     * Gets the value of the inTranAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInTranAmount() {
        return inTranAmount;
    }

    /**
     * Sets the value of the inTranAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInTranAmount(BigDecimal value) {
        this.inTranAmount = value;
    }

    /**
     * Gets the value of the inNgaygd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInNgaygd() {
        return inNgaygd;
    }

    /**
     * Sets the value of the inNgaygd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInNgaygd(String value) {
        this.inNgaygd = value;
    }

    /**
     * Gets the value of the inCashboxNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInCashboxNbr() {
        return inCashboxNbr;
    }

    /**
     * Sets the value of the inCashboxNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInCashboxNbr(String value) {
        this.inCashboxNbr = value;
    }

    /**
     * Gets the value of the inOrigPersNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInOrigPersNbr() {
        return inOrigPersNbr;
    }

    /**
     * Sets the value of the inOrigPersNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInOrigPersNbr(String value) {
        this.inOrigPersNbr = value;
    }

    /**
     * Gets the value of the inApprPersNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInApprPersNbr() {
        return inApprPersNbr;
    }

    /**
     * Sets the value of the inApprPersNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInApprPersNbr(String value) {
        this.inApprPersNbr = value;
    }

    /**
     * Gets the value of the intRtxnDescText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntRtxnDescText() {
        return intRtxnDescText;
    }

    /**
     * Sets the value of the intRtxnDescText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntRtxnDescText(String value) {
        this.intRtxnDescText = value;
    }

    /**
     * Gets the value of the inIsDeposit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInIsDeposit() {
        return inIsDeposit;
    }

    /**
     * Sets the value of the inIsDeposit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInIsDeposit(BigDecimal value) {
        this.inIsDeposit = value;
    }

    /**
     * Gets the value of the inPernbr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInPernbr() {
        return inPernbr;
    }

    /**
     * Sets the value of the inPernbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInPernbr(BigDecimal value) {
        this.inPernbr = value;
    }

    /**
     * Gets the value of the inMJ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInMJ() {
        return inMJ;
    }

    /**
     * Sets the value of the inMJ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInMJ(String value) {
        this.inMJ = value;
    }

    /**
     * Gets the value of the inMI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInMI() {
        return inMI;
    }

    /**
     * Sets the value of the inMI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInMI(String value) {
        this.inMI = value;
    }

    /**
     * Gets the value of the isAllotment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsAllotment() {
        return isAllotment;
    }

    /**
     * Sets the value of the isAllotment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsAllotment(String value) {
        this.isAllotment = value;
    }

}
