//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.08 at 01:42:57 PM NOVT 
//


package vn.unicloud.vietqr.soap.inetservice.model;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="acctnbr" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="tdate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "acctnbr",
    "tdate"
})
@XmlRootElement(name = "GetBalAmtAtDay")
public class GetBalAmtAtDay {

    @XmlElement(required = true)
    protected BigDecimal acctnbr;
    protected String tdate;

    /**
     * Gets the value of the acctnbr property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAcctnbr() {
        return acctnbr;
    }

    /**
     * Sets the value of the acctnbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAcctnbr(BigDecimal value) {
        this.acctnbr = value;
    }

    /**
     * Gets the value of the tdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTdate() {
        return tdate;
    }

    /**
     * Sets the value of the tdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTdate(String value) {
        this.tdate = value;
    }

}
