//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.08 at 01:42:57 PM NOVT 
//


package vn.unicloud.vietqr.soap.inetservice.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sunshinetech.aje.stm.INetService.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SecurityHeader_QNAME = new QName("http://tempuri.org/", "SecurityHeader");
    private final static QName _ProvinceInfoSrz_QNAME = new QName("http://tempuri.org/", "ProvinceInfoSrz");
    private final static QName _ArrayOfString_QNAME = new QName("http://tempuri.org/", "ArrayOfString");
    private final static QName _DataSet_QNAME = new QName("http://tempuri.org/", "DataSet");
    private final static QName _AcctBankCheckSvcInfoSrz_QNAME = new QName("http://tempuri.org/", "AcctBankCheckSvcInfoSrz");
    private final static QName _String_QNAME = new QName("http://tempuri.org/", "string");
    private final static QName _SchedulesInfoSrz_QNAME = new QName("http://tempuri.org/", "SchedulesInfoSrz");
    private final static QName _BankExtInfoSrz_QNAME = new QName("http://tempuri.org/", "BankExtInfoSrz");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sunshinetech.aje.stm.INetService.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TransferOnlineIDCardITNDResponse }
     * 
     */
    public TransferOnlineIDCardITNDResponse createTransferOnlineIDCardITNDResponse() {
        return new TransferOnlineIDCardITNDResponse();
    }

    /**
     * Create an instance of {@link GetInterestEstAmountResponse.GetInterestEstAmountResult }
     * 
     */
    public GetInterestEstAmountResponse.GetInterestEstAmountResult createGetInterestEstAmountResponseGetInterestEstAmountResult() {
        return new GetInterestEstAmountResponse.GetInterestEstAmountResult();
    }

    /**
     * Create an instance of {@link GetTransactionHistoryInfoResponse.GetTransactionHistoryInfoResult }
     * 
     */
    public GetTransactionHistoryInfoResponse.GetTransactionHistoryInfoResult createGetTransactionHistoryInfoResponseGetTransactionHistoryInfoResult() {
        return new GetTransactionHistoryInfoResponse.GetTransactionHistoryInfoResult();
    }

    /**
     * Create an instance of {@link GetAccountByMJAcctTypeCDResponse }
     * 
     */
    public GetAccountByMJAcctTypeCDResponse createGetAccountByMJAcctTypeCDResponse() {
        return new GetAccountByMJAcctTypeCDResponse();
    }

    /**
     * Create an instance of {@link GetAccountByMJAcctTypeCD }
     * 
     */
    public GetAccountByMJAcctTypeCD createGetAccountByMJAcctTypeCD() {
        return new GetAccountByMJAcctTypeCD();
    }

    /**
     * Create an instance of {@link STMGetAccountHolderNameResponse }
     * 
     */
    public STMGetAccountHolderNameResponse createSTMGetAccountHolderNameResponse() {
        return new STMGetAccountHolderNameResponse();
    }

    /**
     * Create an instance of {@link GetBalAmtAtDayResponse }
     * 
     */
    public GetBalAmtAtDayResponse createGetBalAmtAtDayResponse() {
        return new GetBalAmtAtDayResponse();
    }

    /**
     * Create an instance of {@link GetBranchFromChiNhanhTableByOrgNbrResponse.GetBranchFromChiNhanhTableByOrgNbrResult }
     * 
     */
    public GetBranchFromChiNhanhTableByOrgNbrResponse.GetBranchFromChiNhanhTableByOrgNbrResult createGetBranchFromChiNhanhTableByOrgNbrResponseGetBranchFromChiNhanhTableByOrgNbrResult() {
        return new GetBranchFromChiNhanhTableByOrgNbrResponse.GetBranchFromChiNhanhTableByOrgNbrResult();
    }

    /**
     * Create an instance of {@link CancelSchedule }
     * 
     */
    public CancelSchedule createCancelSchedule() {
        return new CancelSchedule();
    }

    /**
     * Create an instance of {@link GetBranchByWhereResponse }
     * 
     */
    public GetBranchByWhereResponse createGetBranchByWhereResponse() {
        return new GetBranchByWhereResponse();
    }

    /**
     * Create an instance of {@link STMDepositCash }
     * 
     */
    public STMDepositCash createSTMDepositCash() {
        return new STMDepositCash();
    }

    /**
     * Create an instance of {@link VoidScheduleByTransIdResponse }
     * 
     */
    public VoidScheduleByTransIdResponse createVoidScheduleByTransIdResponse() {
        return new VoidScheduleByTransIdResponse();
    }

    /**
     * Create an instance of {@link GetAccountInfosResponse.GetAccountInfosResult }
     * 
     */
    public GetAccountInfosResponse.GetAccountInfosResult createGetAccountInfosResponseGetAccountInfosResult() {
        return new GetAccountInfosResponse.GetAccountInfosResult();
    }

    /**
     * Create an instance of {@link GetSavingInterestExpOnlineResponse }
     * 
     */
    public GetSavingInterestExpOnlineResponse createGetSavingInterestExpOnlineResponse() {
        return new GetSavingInterestExpOnlineResponse();
    }

    /**
     * Create an instance of {@link ArrayOfSchedulesInfo }
     * 
     */
    public ArrayOfSchedulesInfo createArrayOfSchedulesInfo() {
        return new ArrayOfSchedulesInfo();
    }

    /**
     * Create an instance of {@link FeeGetFeeAccountOrgResponse }
     * 
     */
    public FeeGetFeeAccountOrgResponse createFeeGetFeeAccountOrgResponse() {
        return new FeeGetFeeAccountOrgResponse();
    }

    /**
     * Create an instance of {@link GetSubAcctNbrResponse }
     * 
     */
    public GetSubAcctNbrResponse createGetSubAcctNbrResponse() {
        return new GetSubAcctNbrResponse();
    }

    /**
     * Create an instance of {@link GetAccountInfosResponse }
     * 
     */
    public GetAccountInfosResponse createGetAccountInfosResponse() {
        return new GetAccountInfosResponse();
    }

    /**
     * Create an instance of {@link GetAccountProduct }
     * 
     */
    public GetAccountProduct createGetAccountProduct() {
        return new GetAccountProduct();
    }

    /**
     * Create an instance of {@link GetTransactionHistoryInfoV2Response }
     * 
     */
    public GetTransactionHistoryInfoV2Response createGetTransactionHistoryInfoV2Response() {
        return new GetTransactionHistoryInfoV2Response();
    }

    /**
     * Create an instance of {@link ProvinceInfoSrz }
     * 
     */
    public ProvinceInfoSrz createProvinceInfoSrz() {
        return new ProvinceInfoSrz();
    }

    /**
     * Create an instance of {@link GetBankInfoByIDResponse }
     * 
     */
    public GetBankInfoByIDResponse createGetBankInfoByIDResponse() {
        return new GetBankInfoByIDResponse();
    }

    /**
     * Create an instance of {@link GetListCardByPerNbrResponse }
     * 
     */
    public GetListCardByPerNbrResponse createGetListCardByPerNbrResponse() {
        return new GetListCardByPerNbrResponse();
    }

    /**
     * Create an instance of {@link CreateFinalizeSavOnline }
     * 
     */
    public CreateFinalizeSavOnline createCreateFinalizeSavOnline() {
        return new CreateFinalizeSavOnline();
    }

    /**
     * Create an instance of {@link GetBranchFromChiNhanhTableByOrgNbr }
     * 
     */
    public GetBranchFromChiNhanhTableByOrgNbr createGetBranchFromChiNhanhTableByOrgNbr() {
        return new GetBranchFromChiNhanhTableByOrgNbr();
    }

    /**
     * Create an instance of {@link CreateScheduleITND }
     * 
     */
    public CreateScheduleITND createCreateScheduleITND() {
        return new CreateScheduleITND();
    }

    /**
     * Create an instance of {@link GetCustomerInfoResponse }
     * 
     */
    public GetCustomerInfoResponse createGetCustomerInfoResponse() {
        return new GetCustomerInfoResponse();
    }

    /**
     * Create an instance of {@link GetSubAcctNbr }
     * 
     */
    public GetSubAcctNbr createGetSubAcctNbr() {
        return new GetSubAcctNbr();
    }

    /**
     * Create an instance of {@link GetCurrentBalanceResponse.GetCurrentBalanceResult }
     * 
     */
    public GetCurrentBalanceResponse.GetCurrentBalanceResult createGetCurrentBalanceResponseGetCurrentBalanceResult() {
        return new GetCurrentBalanceResponse.GetCurrentBalanceResult();
    }

    /**
     * Create an instance of {@link GetTransactionHistoryResponse }
     * 
     */
    public GetTransactionHistoryResponse createGetTransactionHistoryResponse() {
        return new GetTransactionHistoryResponse();
    }

    /**
     * Create an instance of {@link GetScheduleByTransID }
     * 
     */
    public GetScheduleByTransID createGetScheduleByTransID() {
        return new GetScheduleByTransID();
    }

    /**
     * Create an instance of {@link SecurityHeader }
     * 
     */
    public SecurityHeader createSecurityHeader() {
        return new SecurityHeader();
    }

    /**
     * Create an instance of {@link GetAllBalanceInfoResponse.GetAllBalanceInfoResult }
     * 
     */
    public GetAllBalanceInfoResponse.GetAllBalanceInfoResult createGetAllBalanceInfoResponseGetAllBalanceInfoResult() {
        return new GetAllBalanceInfoResponse.GetAllBalanceInfoResult();
    }

    /**
     * Create an instance of {@link GetCustomerInfoByCustNbr }
     * 
     */
    public GetCustomerInfoByCustNbr createGetCustomerInfoByCustNbr() {
        return new GetCustomerInfoByCustNbr();
    }

    /**
     * Create an instance of {@link ArrayOfProvinceInfo }
     * 
     */
    public ArrayOfProvinceInfo createArrayOfProvinceInfo() {
        return new ArrayOfProvinceInfo();
    }

    /**
     * Create an instance of {@link GetBalanceInfoResponse }
     * 
     */
    public GetBalanceInfoResponse createGetBalanceInfoResponse() {
        return new GetBalanceInfoResponse();
    }

    /**
     * Create an instance of {@link ArrayOfString }
     * 
     */
    public ArrayOfString createArrayOfString() {
        return new ArrayOfString();
    }

    /**
     * Create an instance of {@link GetBranch }
     * 
     */
    public GetBranch createGetBranch() {
        return new GetBranch();
    }

    /**
     * Create an instance of {@link GetRateResponse }
     * 
     */
    public GetRateResponse createGetRateResponse() {
        return new GetRateResponse();
    }

    /**
     * Create an instance of {@link TransferOnlineITNDResponse }
     * 
     */
    public TransferOnlineITNDResponse createTransferOnlineITNDResponse() {
        return new TransferOnlineITNDResponse();
    }

    /**
     * Create an instance of {@link GetProvinceInfoByProvince }
     * 
     */
    public GetProvinceInfoByProvince createGetProvinceInfoByProvince() {
        return new GetProvinceInfoByProvince();
    }

    /**
     * Create an instance of {@link GetBranchFromChiNhanhTableByOrgNbrResponse }
     * 
     */
    public GetBranchFromChiNhanhTableByOrgNbrResponse createGetBranchFromChiNhanhTableByOrgNbrResponse() {
        return new GetBranchFromChiNhanhTableByOrgNbrResponse();
    }

    /**
     * Create an instance of {@link InActiveAccounttHoldResponse }
     * 
     */
    public InActiveAccounttHoldResponse createInActiveAccounttHoldResponse() {
        return new InActiveAccounttHoldResponse();
    }

    /**
     * Create an instance of {@link BankExtInfo }
     * 
     */
    public BankExtInfo createBankExtInfo() {
        return new BankExtInfo();
    }

    /**
     * Create an instance of {@link GetAccountProductResponse.GetAccountProductResult }
     * 
     */
    public GetAccountProductResponse.GetAccountProductResult createGetAccountProductResponseGetAccountProductResult() {
        return new GetAccountProductResponse.GetAccountProductResult();
    }

    /**
     * Create an instance of {@link AcctBankCheckSvcInfoSrz }
     * 
     */
    public AcctBankCheckSvcInfoSrz createAcctBankCheckSvcInfoSrz() {
        return new AcctBankCheckSvcInfoSrz();
    }

    /**
     * Create an instance of {@link STMGetAccountHolderName }
     * 
     */
    public STMGetAccountHolderName createSTMGetAccountHolderName() {
        return new STMGetAccountHolderName();
    }

    /**
     * Create an instance of {@link AccountHoldResponse }
     * 
     */
    public AccountHoldResponse createAccountHoldResponse() {
        return new AccountHoldResponse();
    }

    /**
     * Create an instance of {@link GetAccountProductByAcct }
     * 
     */
    public GetAccountProductByAcct createGetAccountProductByAcct() {
        return new GetAccountProductByAcct();
    }

    /**
     * Create an instance of {@link STMWithDrawalRevResponse }
     * 
     */
    public STMWithDrawalRevResponse createSTMWithDrawalRevResponse() {
        return new STMWithDrawalRevResponse();
    }

    /**
     * Create an instance of {@link GetSavingInterestExpOnline }
     * 
     */
    public GetSavingInterestExpOnline createGetSavingInterestExpOnline() {
        return new GetSavingInterestExpOnline();
    }

    /**
     * Create an instance of {@link GetCustomerIDByProduct }
     * 
     */
    public GetCustomerIDByProduct createGetCustomerIDByProduct() {
        return new GetCustomerIDByProduct();
    }

    /**
     * Create an instance of {@link GetBranchResponse }
     * 
     */
    public GetBranchResponse createGetBranchResponse() {
        return new GetBranchResponse();
    }

    /**
     * Create an instance of {@link SchedulesInfo }
     * 
     */
    public SchedulesInfo createSchedulesInfo() {
        return new SchedulesInfo();
    }

    /**
     * Create an instance of {@link ArrayOfAcctBankCheckSvcInfo }
     * 
     */
    public ArrayOfAcctBankCheckSvcInfo createArrayOfAcctBankCheckSvcInfo() {
        return new ArrayOfAcctBankCheckSvcInfo();
    }

    /**
     * Create an instance of {@link GetTransactionHistory }
     * 
     */
    public GetTransactionHistory createGetTransactionHistory() {
        return new GetTransactionHistory();
    }

    /**
     * Create an instance of {@link GetCustomerInfoByAcctNbrResponse }
     * 
     */
    public GetCustomerInfoByAcctNbrResponse createGetCustomerInfoByAcctNbrResponse() {
        return new GetCustomerInfoByAcctNbrResponse();
    }

    /**
     * Create an instance of {@link CreateDepositOnlineResponse }
     * 
     */
    public CreateDepositOnlineResponse createCreateDepositOnlineResponse() {
        return new CreateDepositOnlineResponse();
    }

    /**
     * Create an instance of {@link TransferOnline }
     * 
     */
    public TransferOnline createTransferOnline() {
        return new TransferOnline();
    }

    /**
     * Create an instance of {@link GetInterestHistory }
     * 
     */
    public GetInterestHistory createGetInterestHistory() {
        return new GetInterestHistory();
    }

    /**
     * Create an instance of {@link GetBranchByOrgNbr }
     * 
     */
    public GetBranchByOrgNbr createGetBranchByOrgNbr() {
        return new GetBranchByOrgNbr();
    }

    /**
     * Create an instance of {@link GetCustInfoBalance }
     * 
     */
    public GetCustInfoBalance createGetCustInfoBalance() {
        return new GetCustInfoBalance();
    }

    /**
     * Create an instance of {@link GetPlaceRegAcctByAcctNbrResponse }
     * 
     */
    public GetPlaceRegAcctByAcctNbrResponse createGetPlaceRegAcctByAcctNbrResponse() {
        return new GetPlaceRegAcctByAcctNbrResponse();
    }

    /**
     * Create an instance of {@link GetByExtCheckNbrResponse }
     * 
     */
    public GetByExtCheckNbrResponse createGetByExtCheckNbrResponse() {
        return new GetByExtCheckNbrResponse();
    }

    /**
     * Create an instance of {@link ArrayOfBankExtInfo }
     * 
     */
    public ArrayOfBankExtInfo createArrayOfBankExtInfo() {
        return new ArrayOfBankExtInfo();
    }

    /**
     * Create an instance of {@link GetBalAmtAtDay }
     * 
     */
    public GetBalAmtAtDay createGetBalAmtAtDay() {
        return new GetBalAmtAtDay();
    }

    /**
     * Create an instance of {@link STMCreatePer }
     * 
     */
    public STMCreatePer createSTMCreatePer() {
        return new STMCreatePer();
    }

    /**
     * Create an instance of {@link GetBranchByWhere }
     * 
     */
    public GetBranchByWhere createGetBranchByWhere() {
        return new GetBranchByWhere();
    }

    /**
     * Create an instance of {@link GetTransactionHistoryResponse.GetTransactionHistoryResult }
     * 
     */
    public GetTransactionHistoryResponse.GetTransactionHistoryResult createGetTransactionHistoryResponseGetTransactionHistoryResult() {
        return new GetTransactionHistoryResponse.GetTransactionHistoryResult();
    }

    /**
     * Create an instance of {@link GetTaxCtryCD }
     * 
     */
    public GetTaxCtryCD createGetTaxCtryCD() {
        return new GetTaxCtryCD();
    }

    /**
     * Create an instance of {@link GetInterestEstAmountResponse }
     * 
     */
    public GetInterestEstAmountResponse createGetInterestEstAmountResponse() {
        return new GetInterestEstAmountResponse();
    }

    /**
     * Create an instance of {@link GetCustomerInfoByCustNbrResponse }
     * 
     */
    public GetCustomerInfoByCustNbrResponse createGetCustomerInfoByCustNbrResponse() {
        return new GetCustomerInfoByCustNbrResponse();
    }

    /**
     * Create an instance of {@link GetPDATCDATResponse }
     * 
     */
    public GetPDATCDATResponse createGetPDATCDATResponse() {
        return new GetPDATCDATResponse();
    }

    /**
     * Create an instance of {@link GetCustomerIDByProductResponse.GetCustomerIDByProductResult }
     * 
     */
    public GetCustomerIDByProductResponse.GetCustomerIDByProductResult createGetCustomerIDByProductResponseGetCustomerIDByProductResult() {
        return new GetCustomerIDByProductResponse.GetCustomerIDByProductResult();
    }

    /**
     * Create an instance of {@link GetBankInfoAllResponse }
     * 
     */
    public GetBankInfoAllResponse createGetBankInfoAllResponse() {
        return new GetBankInfoAllResponse();
    }

    /**
     * Create an instance of {@link STMWithDrawalRev }
     * 
     */
    public STMWithDrawalRev createSTMWithDrawalRev() {
        return new STMWithDrawalRev();
    }

    /**
     * Create an instance of {@link AcctBankCheckSvcInfo }
     * 
     */
    public AcctBankCheckSvcInfo createAcctBankCheckSvcInfo() {
        return new AcctBankCheckSvcInfo();
    }

    /**
     * Create an instance of {@link GetTransactionHistoryInfo }
     * 
     */
    public GetTransactionHistoryInfo createGetTransactionHistoryInfo() {
        return new GetTransactionHistoryInfo();
    }

    /**
     * Create an instance of {@link GetTransactionHistoryDetailResponse.GetTransactionHistoryDetailResult }
     * 
     */
    public GetTransactionHistoryDetailResponse.GetTransactionHistoryDetailResult createGetTransactionHistoryDetailResponseGetTransactionHistoryDetailResult() {
        return new GetTransactionHistoryDetailResponse.GetTransactionHistoryDetailResult();
    }

    /**
     * Create an instance of {@link GetTransactionHistoryDetailResponse }
     * 
     */
    public GetTransactionHistoryDetailResponse createGetTransactionHistoryDetailResponse() {
        return new GetTransactionHistoryDetailResponse();
    }

    /**
     * Create an instance of {@link GetBalanceInfoDetailsResponse }
     * 
     */
    public GetBalanceInfoDetailsResponse createGetBalanceInfoDetailsResponse() {
        return new GetBalanceInfoDetailsResponse();
    }

    /**
     * Create an instance of {@link GetBalanceInfoDetails }
     * 
     */
    public GetBalanceInfoDetails createGetBalanceInfoDetails() {
        return new GetBalanceInfoDetails();
    }

    /**
     * Create an instance of {@link TransferOnlineIDCardITND }
     * 
     */
    public TransferOnlineIDCardITND createTransferOnlineIDCardITND() {
        return new TransferOnlineIDCardITND();
    }

    /**
     * Create an instance of {@link GetBalanceInfoResponse.GetBalanceInfoResult }
     * 
     */
    public GetBalanceInfoResponse.GetBalanceInfoResult createGetBalanceInfoResponseGetBalanceInfoResult() {
        return new GetBalanceInfoResponse.GetBalanceInfoResult();
    }

    /**
     * Create an instance of {@link GetBranchFromChiNhanhTableByWhereResponse }
     * 
     */
    public GetBranchFromChiNhanhTableByWhereResponse createGetBranchFromChiNhanhTableByWhereResponse() {
        return new GetBranchFromChiNhanhTableByWhereResponse();
    }

    /**
     * Create an instance of {@link BankExtInfoSrz }
     * 
     */
    public BankExtInfoSrz createBankExtInfoSrz() {
        return new BankExtInfoSrz();
    }

    /**
     * Create an instance of {@link GetBranchFromChiNhanhTableByWhereResponse.GetBranchFromChiNhanhTableByWhereResult }
     * 
     */
    public GetBranchFromChiNhanhTableByWhereResponse.GetBranchFromChiNhanhTableByWhereResult createGetBranchFromChiNhanhTableByWhereResponseGetBranchFromChiNhanhTableByWhereResult() {
        return new GetBranchFromChiNhanhTableByWhereResponse.GetBranchFromChiNhanhTableByWhereResult();
    }

    /**
     * Create an instance of {@link InActiveAccounttHold }
     * 
     */
    public InActiveAccounttHold createInActiveAccounttHold() {
        return new InActiveAccounttHold();
    }

    /**
     * Create an instance of {@link GetAccountByMJAcctTypeCDResponse.GetAccountByMJAcctTypeCDResult }
     * 
     */
    public GetAccountByMJAcctTypeCDResponse.GetAccountByMJAcctTypeCDResult createGetAccountByMJAcctTypeCDResponseGetAccountByMJAcctTypeCDResult() {
        return new GetAccountByMJAcctTypeCDResponse.GetAccountByMJAcctTypeCDResult();
    }

    /**
     * Create an instance of {@link GetInterestHistoryResponse }
     * 
     */
    public GetInterestHistoryResponse createGetInterestHistoryResponse() {
        return new GetInterestHistoryResponse();
    }

    /**
     * Create an instance of {@link GetBranchByOrgNbrResponse }
     * 
     */
    public GetBranchByOrgNbrResponse createGetBranchByOrgNbrResponse() {
        return new GetBranchByOrgNbrResponse();
    }

    /**
     * Create an instance of {@link GetBalanceInfo }
     * 
     */
    public GetBalanceInfo createGetBalanceInfo() {
        return new GetBalanceInfo();
    }

    /**
     * Create an instance of {@link GetBankInfoByProvinceResponse }
     * 
     */
    public GetBankInfoByProvinceResponse createGetBankInfoByProvinceResponse() {
        return new GetBankInfoByProvinceResponse();
    }

    /**
     * Create an instance of {@link GetTransactionHistoryDetail }
     * 
     */
    public GetTransactionHistoryDetail createGetTransactionHistoryDetail() {
        return new GetTransactionHistoryDetail();
    }

    /**
     * Create an instance of {@link GetBranchFromChiNhanhTableByWhere }
     * 
     */
    public GetBranchFromChiNhanhTableByWhere createGetBranchFromChiNhanhTableByWhere() {
        return new GetBranchFromChiNhanhTableByWhere();
    }

    /**
     * Create an instance of {@link GetCurrentBalance }
     * 
     */
    public GetCurrentBalance createGetCurrentBalance() {
        return new GetCurrentBalance();
    }

    /**
     * Create an instance of {@link GetCurrMIAcctTypCDByProduct }
     * 
     */
    public GetCurrMIAcctTypCDByProduct createGetCurrMIAcctTypCDByProduct() {
        return new GetCurrMIAcctTypCDByProduct();
    }

    /**
     * Create an instance of {@link GetRateResponse.GetRateResult }
     * 
     */
    public GetRateResponse.GetRateResult createGetRateResponseGetRateResult() {
        return new GetRateResponse.GetRateResult();
    }

    /**
     * Create an instance of {@link GetPDATCDAT }
     * 
     */
    public GetPDATCDAT createGetPDATCDAT() {
        return new GetPDATCDAT();
    }

    /**
     * Create an instance of {@link GetCurrentBalanceResponse }
     * 
     */
    public GetCurrentBalanceResponse createGetCurrentBalanceResponse() {
        return new GetCurrentBalanceResponse();
    }

    /**
     * Create an instance of {@link STMGetAddressPer }
     * 
     */
    public STMGetAddressPer createSTMGetAddressPer() {
        return new STMGetAddressPer();
    }

    /**
     * Create an instance of {@link GetTransactionHistoryInfoV2 }
     * 
     */
    public GetTransactionHistoryInfoV2 createGetTransactionHistoryInfoV2() {
        return new GetTransactionHistoryInfoV2();
    }

    /**
     * Create an instance of {@link STMUpdateAddressPerResponse }
     * 
     */
    public STMUpdateAddressPerResponse createSTMUpdateAddressPerResponse() {
        return new STMUpdateAddressPerResponse();
    }

    /**
     * Create an instance of {@link STMCreateVipAccountResponse }
     * 
     */
    public STMCreateVipAccountResponse createSTMCreateVipAccountResponse() {
        return new STMCreateVipAccountResponse();
    }

    /**
     * Create an instance of {@link DataSet }
     * 
     */
    public DataSet createDataSet() {
        return new DataSet();
    }

    /**
     * Create an instance of {@link GetBankInfoAll }
     * 
     */
    public GetBankInfoAll createGetBankInfoAll() {
        return new GetBankInfoAll();
    }

    /**
     * Create an instance of {@link GetByBankCheckNbr }
     * 
     */
    public GetByBankCheckNbr createGetByBankCheckNbr() {
        return new GetByBankCheckNbr();
    }

    /**
     * Create an instance of {@link CreateScheduleResponse }
     * 
     */
    public CreateScheduleResponse createCreateScheduleResponse() {
        return new CreateScheduleResponse();
    }

    /**
     * Create an instance of {@link TransferOnlineIDCardResponse }
     * 
     */
    public TransferOnlineIDCardResponse createTransferOnlineIDCardResponse() {
        return new TransferOnlineIDCardResponse();
    }

    /**
     * Create an instance of {@link STMCreatePerResponse }
     * 
     */
    public STMCreatePerResponse createSTMCreatePerResponse() {
        return new STMCreatePerResponse();
    }

    /**
     * Create an instance of {@link GetBankInfoByID }
     * 
     */
    public GetBankInfoByID createGetBankInfoByID() {
        return new GetBankInfoByID();
    }

    /**
     * Create an instance of {@link GetAccountInfos }
     * 
     */
    public GetAccountInfos createGetAccountInfos() {
        return new GetAccountInfos();
    }

    /**
     * Create an instance of {@link GetScheduleByExtCheckNbrResponse }
     * 
     */
    public GetScheduleByExtCheckNbrResponse createGetScheduleByExtCheckNbrResponse() {
        return new GetScheduleByExtCheckNbrResponse();
    }

    /**
     * Create an instance of {@link GetProvinceInfoByProvinceResponse }
     * 
     */
    public GetProvinceInfoByProvinceResponse createGetProvinceInfoByProvinceResponse() {
        return new GetProvinceInfoByProvinceResponse();
    }

    /**
     * Create an instance of {@link GetBranchFromChiNhanhTable }
     * 
     */
    public GetBranchFromChiNhanhTable createGetBranchFromChiNhanhTable() {
        return new GetBranchFromChiNhanhTable();
    }

    /**
     * Create an instance of {@link GetBankInfoByProvince }
     * 
     */
    public GetBankInfoByProvince createGetBankInfoByProvince() {
        return new GetBankInfoByProvince();
    }

    /**
     * Create an instance of {@link STMGetAccountByCardNoResponse }
     * 
     */
    public STMGetAccountByCardNoResponse createSTMGetAccountByCardNoResponse() {
        return new STMGetAccountByCardNoResponse();
    }

    /**
     * Create an instance of {@link GetAccountProductByAcctResponse }
     * 
     */
    public GetAccountProductByAcctResponse createGetAccountProductByAcctResponse() {
        return new GetAccountProductByAcctResponse();
    }

    /**
     * Create an instance of {@link STMWithDrawal }
     * 
     */
    public STMWithDrawal createSTMWithDrawal() {
        return new STMWithDrawal();
    }

    /**
     * Create an instance of {@link GetByBankCheckNbrResponse }
     * 
     */
    public GetByBankCheckNbrResponse createGetByBankCheckNbrResponse() {
        return new GetByBankCheckNbrResponse();
    }

    /**
     * Create an instance of {@link VoidScheduleByTransId }
     * 
     */
    public VoidScheduleByTransId createVoidScheduleByTransId() {
        return new VoidScheduleByTransId();
    }

    /**
     * Create an instance of {@link ProvinceInfo }
     * 
     */
    public ProvinceInfo createProvinceInfo() {
        return new ProvinceInfo();
    }

    /**
     * Create an instance of {@link FeeGetFeeAccountOrg }
     * 
     */
    public FeeGetFeeAccountOrg createFeeGetFeeAccountOrg() {
        return new FeeGetFeeAccountOrg();
    }

    /**
     * Create an instance of {@link GetAllBalanceInfo }
     * 
     */
    public GetAllBalanceInfo createGetAllBalanceInfo() {
        return new GetAllBalanceInfo();
    }

    /**
     * Create an instance of {@link GetBranchFromChiNhanhTableResponse.GetBranchFromChiNhanhTableResult }
     * 
     */
    public GetBranchFromChiNhanhTableResponse.GetBranchFromChiNhanhTableResult createGetBranchFromChiNhanhTableResponseGetBranchFromChiNhanhTableResult() {
        return new GetBranchFromChiNhanhTableResponse.GetBranchFromChiNhanhTableResult();
    }

    /**
     * Create an instance of {@link STMUpdateAddressPer }
     * 
     */
    public STMUpdateAddressPer createSTMUpdateAddressPer() {
        return new STMUpdateAddressPer();
    }

    /**
     * Create an instance of {@link GetInterestHistoryResponse.GetInterestHistoryResult }
     * 
     */
    public GetInterestHistoryResponse.GetInterestHistoryResult createGetInterestHistoryResponseGetInterestHistoryResult() {
        return new GetInterestHistoryResponse.GetInterestHistoryResult();
    }

    /**
     * Create an instance of {@link GetAllBalanceInfoResponse }
     * 
     */
    public GetAllBalanceInfoResponse createGetAllBalanceInfoResponse() {
        return new GetAllBalanceInfoResponse();
    }

    /**
     * Create an instance of {@link GetContractDateByAcctNbrResponse }
     * 
     */
    public GetContractDateByAcctNbrResponse createGetContractDateByAcctNbrResponse() {
        return new GetContractDateByAcctNbrResponse();
    }

    /**
     * Create an instance of {@link GetBranchByWhereResponse.GetBranchByWhereResult }
     * 
     */
    public GetBranchByWhereResponse.GetBranchByWhereResult createGetBranchByWhereResponseGetBranchByWhereResult() {
        return new GetBranchByWhereResponse.GetBranchByWhereResult();
    }

    /**
     * Create an instance of {@link GetCustomerInfoByAcctNbr }
     * 
     */
    public GetCustomerInfoByAcctNbr createGetCustomerInfoByAcctNbr() {
        return new GetCustomerInfoByAcctNbr();
    }

    /**
     * Create an instance of {@link GetInterestEstAmount }
     * 
     */
    public GetInterestEstAmount createGetInterestEstAmount() {
        return new GetInterestEstAmount();
    }

    /**
     * Create an instance of {@link GetCurrMIAcctTypCDByProductResponse }
     * 
     */
    public GetCurrMIAcctTypCDByProductResponse createGetCurrMIAcctTypCDByProductResponse() {
        return new GetCurrMIAcctTypCDByProductResponse();
    }

    /**
     * Create an instance of {@link GetScheduleByFrAccountResponse }
     * 
     */
    public GetScheduleByFrAccountResponse createGetScheduleByFrAccountResponse() {
        return new GetScheduleByFrAccountResponse();
    }

    /**
     * Create an instance of {@link STMDepositCashResponse }
     * 
     */
    public STMDepositCashResponse createSTMDepositCashResponse() {
        return new STMDepositCashResponse();
    }

    /**
     * Create an instance of {@link TransferOnlineIDCard }
     * 
     */
    public TransferOnlineIDCard createTransferOnlineIDCard() {
        return new TransferOnlineIDCard();
    }

    /**
     * Create an instance of {@link GetScheduleByStatus }
     * 
     */
    public GetScheduleByStatus createGetScheduleByStatus() {
        return new GetScheduleByStatus();
    }

    /**
     * Create an instance of {@link GetRate }
     * 
     */
    public GetRate createGetRate() {
        return new GetRate();
    }

    /**
     * Create an instance of {@link GetPayToByAcctNbrExtCheckNbr }
     * 
     */
    public GetPayToByAcctNbrExtCheckNbr createGetPayToByAcctNbrExtCheckNbr() {
        return new GetPayToByAcctNbrExtCheckNbr();
    }

    /**
     * Create an instance of {@link STMCreateVipAccount }
     * 
     */
    public STMCreateVipAccount createSTMCreateVipAccount() {
        return new STMCreateVipAccount();
    }

    /**
     * Create an instance of {@link GetPlaceRegAcctByAcctNbr }
     * 
     */
    public GetPlaceRegAcctByAcctNbr createGetPlaceRegAcctByAcctNbr() {
        return new GetPlaceRegAcctByAcctNbr();
    }

    /**
     * Create an instance of {@link GetCustomerIDByProductResponse }
     * 
     */
    public GetCustomerIDByProductResponse createGetCustomerIDByProductResponse() {
        return new GetCustomerIDByProductResponse();
    }

    /**
     * Create an instance of {@link STMGetAccountByCardNo }
     * 
     */
    public STMGetAccountByCardNo createSTMGetAccountByCardNo() {
        return new STMGetAccountByCardNo();
    }

    /**
     * Create an instance of {@link GetBranchFromChiNhanhTableResponse }
     * 
     */
    public GetBranchFromChiNhanhTableResponse createGetBranchFromChiNhanhTableResponse() {
        return new GetBranchFromChiNhanhTableResponse();
    }

    /**
     * Create an instance of {@link GetInterestSavingEstResponse }
     * 
     */
    public GetInterestSavingEstResponse createGetInterestSavingEstResponse() {
        return new GetInterestSavingEstResponse();
    }

    /**
     * Create an instance of {@link TransferOnlineResponse }
     * 
     */
    public TransferOnlineResponse createTransferOnlineResponse() {
        return new TransferOnlineResponse();
    }

    /**
     * Create an instance of {@link GetScheduleByStatusResponse }
     * 
     */
    public GetScheduleByStatusResponse createGetScheduleByStatusResponse() {
        return new GetScheduleByStatusResponse();
    }

    /**
     * Create an instance of {@link STMGetAddressPerResponse }
     * 
     */
    public STMGetAddressPerResponse createSTMGetAddressPerResponse() {
        return new STMGetAddressPerResponse();
    }

    /**
     * Create an instance of {@link GetByExtCheckNbr }
     * 
     */
    public GetByExtCheckNbr createGetByExtCheckNbr() {
        return new GetByExtCheckNbr();
    }

    /**
     * Create an instance of {@link GetProvinceInfoAllResponse }
     * 
     */
    public GetProvinceInfoAllResponse createGetProvinceInfoAllResponse() {
        return new GetProvinceInfoAllResponse();
    }

    /**
     * Create an instance of {@link GetTaxCtryCDResponse }
     * 
     */
    public GetTaxCtryCDResponse createGetTaxCtryCDResponse() {
        return new GetTaxCtryCDResponse();
    }

    /**
     * Create an instance of {@link GetCustInfoBalanceResponse }
     * 
     */
    public GetCustInfoBalanceResponse createGetCustInfoBalanceResponse() {
        return new GetCustInfoBalanceResponse();
    }

    /**
     * Create an instance of {@link GetScheduleByTransIDResponse }
     * 
     */
    public GetScheduleByTransIDResponse createGetScheduleByTransIDResponse() {
        return new GetScheduleByTransIDResponse();
    }

    /**
     * Create an instance of {@link CreateSchedule }
     * 
     */
    public CreateSchedule createCreateSchedule() {
        return new CreateSchedule();
    }

    /**
     * Create an instance of {@link GetScheduleByFrAccount }
     * 
     */
    public GetScheduleByFrAccount createGetScheduleByFrAccount() {
        return new GetScheduleByFrAccount();
    }

    /**
     * Create an instance of {@link GetContractDateByAcctNbr }
     * 
     */
    public GetContractDateByAcctNbr createGetContractDateByAcctNbr() {
        return new GetContractDateByAcctNbr();
    }

    /**
     * Create an instance of {@link CreateFinalizeSavOnlineResponse }
     * 
     */
    public CreateFinalizeSavOnlineResponse createCreateFinalizeSavOnlineResponse() {
        return new CreateFinalizeSavOnlineResponse();
    }

    /**
     * Create an instance of {@link GetPayToByAcctNbrExtCheckNbrResponse }
     * 
     */
    public GetPayToByAcctNbrExtCheckNbrResponse createGetPayToByAcctNbrExtCheckNbrResponse() {
        return new GetPayToByAcctNbrExtCheckNbrResponse();
    }

    /**
     * Create an instance of {@link CreateScheduleITNDResponse }
     * 
     */
    public CreateScheduleITNDResponse createCreateScheduleITNDResponse() {
        return new CreateScheduleITNDResponse();
    }

    /**
     * Create an instance of {@link STMCreateAccount }
     * 
     */
    public STMCreateAccount createSTMCreateAccount() {
        return new STMCreateAccount();
    }

    /**
     * Create an instance of {@link GetBranchResponse.GetBranchResult }
     * 
     */
    public GetBranchResponse.GetBranchResult createGetBranchResponseGetBranchResult() {
        return new GetBranchResponse.GetBranchResult();
    }

    /**
     * Create an instance of {@link STMWithDrawalResponse }
     * 
     */
    public STMWithDrawalResponse createSTMWithDrawalResponse() {
        return new STMWithDrawalResponse();
    }

    /**
     * Create an instance of {@link GetScheduleByExtCheckNbr }
     * 
     */
    public GetScheduleByExtCheckNbr createGetScheduleByExtCheckNbr() {
        return new GetScheduleByExtCheckNbr();
    }

    /**
     * Create an instance of {@link AccountHold }
     * 
     */
    public AccountHold createAccountHold() {
        return new AccountHold();
    }

    /**
     * Create an instance of {@link GetInterestSavingEstResponse.GetInterestSavingEstResult }
     * 
     */
    public GetInterestSavingEstResponse.GetInterestSavingEstResult createGetInterestSavingEstResponseGetInterestSavingEstResult() {
        return new GetInterestSavingEstResponse.GetInterestSavingEstResult();
    }

    /**
     * Create an instance of {@link GetCustomerInfo }
     * 
     */
    public GetCustomerInfo createGetCustomerInfo() {
        return new GetCustomerInfo();
    }

    /**
     * Create an instance of {@link GetListCardByPerNbr }
     * 
     */
    public GetListCardByPerNbr createGetListCardByPerNbr() {
        return new GetListCardByPerNbr();
    }

    /**
     * Create an instance of {@link GetListCardByPerNbrResponse.GetListCardByPerNbrResult }
     * 
     */
    public GetListCardByPerNbrResponse.GetListCardByPerNbrResult createGetListCardByPerNbrResponseGetListCardByPerNbrResult() {
        return new GetListCardByPerNbrResponse.GetListCardByPerNbrResult();
    }

    /**
     * Create an instance of {@link GetBranchByOrgNbrResponse.GetBranchByOrgNbrResult }
     * 
     */
    public GetBranchByOrgNbrResponse.GetBranchByOrgNbrResult createGetBranchByOrgNbrResponseGetBranchByOrgNbrResult() {
        return new GetBranchByOrgNbrResponse.GetBranchByOrgNbrResult();
    }

    /**
     * Create an instance of {@link CancelScheduleResponse }
     * 
     */
    public CancelScheduleResponse createCancelScheduleResponse() {
        return new CancelScheduleResponse();
    }

    /**
     * Create an instance of {@link CreateDepositOnline }
     * 
     */
    public CreateDepositOnline createCreateDepositOnline() {
        return new CreateDepositOnline();
    }

    /**
     * Create an instance of {@link GetInterestSavingEst }
     * 
     */
    public GetInterestSavingEst createGetInterestSavingEst() {
        return new GetInterestSavingEst();
    }

    /**
     * Create an instance of {@link STMCreateAccountResponse }
     * 
     */
    public STMCreateAccountResponse createSTMCreateAccountResponse() {
        return new STMCreateAccountResponse();
    }

    /**
     * Create an instance of {@link GetTransactionHistoryInfoV2Response.GetTransactionHistoryInfoV2Result }
     * 
     */
    public GetTransactionHistoryInfoV2Response.GetTransactionHistoryInfoV2Result createGetTransactionHistoryInfoV2ResponseGetTransactionHistoryInfoV2Result() {
        return new GetTransactionHistoryInfoV2Response.GetTransactionHistoryInfoV2Result();
    }

    /**
     * Create an instance of {@link GetProvinceInfoAll }
     * 
     */
    public GetProvinceInfoAll createGetProvinceInfoAll() {
        return new GetProvinceInfoAll();
    }

    /**
     * Create an instance of {@link TransferOnlineITND }
     * 
     */
    public TransferOnlineITND createTransferOnlineITND() {
        return new TransferOnlineITND();
    }

    /**
     * Create an instance of {@link GetAccountProductResponse }
     * 
     */
    public GetAccountProductResponse createGetAccountProductResponse() {
        return new GetAccountProductResponse();
    }

    /**
     * Create an instance of {@link GetTransactionHistoryInfoResponse }
     * 
     */
    public GetTransactionHistoryInfoResponse createGetTransactionHistoryInfoResponse() {
        return new GetTransactionHistoryInfoResponse();
    }

    /**
     * Create an instance of {@link GetBalanceInfoDetailsResponse.GetBalanceInfoDetailsResult }
     * 
     */
    public GetBalanceInfoDetailsResponse.GetBalanceInfoDetailsResult createGetBalanceInfoDetailsResponseGetBalanceInfoDetailsResult() {
        return new GetBalanceInfoDetailsResponse.GetBalanceInfoDetailsResult();
    }

    /**
     * Create an instance of {@link SchedulesInfoSrz }
     * 
     */
    public SchedulesInfoSrz createSchedulesInfoSrz() {
        return new SchedulesInfoSrz();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "SecurityHeader")
    public JAXBElement<SecurityHeader> createSecurityHeader(SecurityHeader value) {
        return new JAXBElement<SecurityHeader>(_SecurityHeader_QNAME, SecurityHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProvinceInfoSrz }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ProvinceInfoSrz")
    public JAXBElement<ProvinceInfoSrz> createProvinceInfoSrz(ProvinceInfoSrz value) {
        return new JAXBElement<ProvinceInfoSrz>(_ProvinceInfoSrz_QNAME, ProvinceInfoSrz.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfString }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "ArrayOfString")
    public JAXBElement<ArrayOfString> createArrayOfString(ArrayOfString value) {
        return new JAXBElement<ArrayOfString>(_ArrayOfString_QNAME, ArrayOfString.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "DataSet")
    public JAXBElement<DataSet> createDataSet(DataSet value) {
        return new JAXBElement<DataSet>(_DataSet_QNAME, DataSet.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AcctBankCheckSvcInfoSrz }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "AcctBankCheckSvcInfoSrz")
    public JAXBElement<AcctBankCheckSvcInfoSrz> createAcctBankCheckSvcInfoSrz(AcctBankCheckSvcInfoSrz value) {
        return new JAXBElement<AcctBankCheckSvcInfoSrz>(_AcctBankCheckSvcInfoSrz_QNAME, AcctBankCheckSvcInfoSrz.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "string")
    public JAXBElement<String> createString(String value) {
        return new JAXBElement<String>(_String_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SchedulesInfoSrz }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "SchedulesInfoSrz")
    public JAXBElement<SchedulesInfoSrz> createSchedulesInfoSrz(SchedulesInfoSrz value) {
        return new JAXBElement<SchedulesInfoSrz>(_SchedulesInfoSrz_QNAME, SchedulesInfoSrz.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BankExtInfoSrz }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "BankExtInfoSrz")
    public JAXBElement<BankExtInfoSrz> createBankExtInfoSrz(BankExtInfoSrz value) {
        return new JAXBElement<BankExtInfoSrz>(_BankExtInfoSrz_QNAME, BankExtInfoSrz.class, null, value);
    }

}
