//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.08 at 01:42:57 PM NOVT 
//


package vn.unicloud.vietqr.soap.inetservice.model;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fromCustomerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fromCardNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fromIdCard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isMyAcct" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toCk_AcctNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tranAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="descText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fromCustomerName",
    "fromCardNo",
    "fromIdCard",
    "isMyAcct",
    "toCkAcctNbr",
    "tranAmount",
    "descText"
})
@XmlRootElement(name = "STM_Deposit_Cash")
public class STMDepositCash {

    protected String fromCustomerName;
    protected String fromCardNo;
    protected String fromIdCard;
    protected String isMyAcct;
    @XmlElement(name = "toCk_AcctNbr")
    protected String toCkAcctNbr;
    @XmlElement(required = true)
    protected BigDecimal tranAmount;
    protected String descText;

    /**
     * Gets the value of the fromCustomerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromCustomerName() {
        return fromCustomerName;
    }

    /**
     * Sets the value of the fromCustomerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromCustomerName(String value) {
        this.fromCustomerName = value;
    }

    /**
     * Gets the value of the fromCardNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromCardNo() {
        return fromCardNo;
    }

    /**
     * Sets the value of the fromCardNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromCardNo(String value) {
        this.fromCardNo = value;
    }

    /**
     * Gets the value of the fromIdCard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromIdCard() {
        return fromIdCard;
    }

    /**
     * Sets the value of the fromIdCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromIdCard(String value) {
        this.fromIdCard = value;
    }

    /**
     * Gets the value of the isMyAcct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsMyAcct() {
        return isMyAcct;
    }

    /**
     * Sets the value of the isMyAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsMyAcct(String value) {
        this.isMyAcct = value;
    }

    /**
     * Gets the value of the toCkAcctNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToCkAcctNbr() {
        return toCkAcctNbr;
    }

    /**
     * Sets the value of the toCkAcctNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToCkAcctNbr(String value) {
        this.toCkAcctNbr = value;
    }

    /**
     * Gets the value of the tranAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTranAmount() {
        return tranAmount;
    }

    /**
     * Sets the value of the tranAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTranAmount(BigDecimal value) {
        this.tranAmount = value;
    }

    /**
     * Gets the value of the descText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescText() {
        return descText;
    }

    /**
     * Sets the value of the descText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescText(String value) {
        this.descText = value;
    }

}
