//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.08 at 01:42:57 PM NOVT 
//


package vn.unicloud.vietqr.soap.inetservice.model;

import javax.xml.bind.annotation.*;
import java.util.Objects;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="STM_Deposit_CashResult" type="{http://tempuri.org/}ArrayOfString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stmDepositCashResult"
})
@XmlRootElement(name = "STM_Deposit_CashResponse")
public class STMDepositCashResponse {

    @XmlElement(name = "STM_Deposit_CashResult")
    protected ArrayOfString stmDepositCashResult;

    /**
     * Gets the value of the stmDepositCashResult property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getSTMDepositCashResult() {
        return stmDepositCashResult;
    }

    /**
     * Sets the value of the stmDepositCashResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setSTMDepositCashResult(ArrayOfString value) {
        this.stmDepositCashResult = value;
    }

    public boolean isSuccess(){
        if (Objects.isNull(getSTMDepositCashResult().getString().get(2))){
            return false;
        }
        return getSTMDepositCashResult().getString().get(2).equals("00");
    }

    public String getError(){
        return getSTMDepositCashResult().getString().get(4);
    }
    public String getAccountBalance(){
        return getSTMDepositCashResult().getString().get(5);
    }

}
