//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.08 at 01:42:57 PM NOVT 
//


package vn.unicloud.vietqr.soap.inetservice.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="STM_GetAccountByCardNoResult" type="{http://tempuri.org/}ArrayOfString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stmGetAccountByCardNoResult"
})
@XmlRootElement(name = "STM_GetAccountByCardNoResponse")
public class STMGetAccountByCardNoResponse {

    @XmlElement(name = "STM_GetAccountByCardNoResult")
    protected ArrayOfString stmGetAccountByCardNoResult;

    /**
     * Gets the value of the stmGetAccountByCardNoResult property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getSTMGetAccountByCardNoResult() {
        return stmGetAccountByCardNoResult;
    }

    /**
     * Sets the value of the stmGetAccountByCardNoResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setSTMGetAccountByCardNoResult(ArrayOfString value) {
        this.stmGetAccountByCardNoResult = value;
    }

    public boolean isSuccess(){
        return getSTMGetAccountByCardNoResult().getString().get(1).equals("00");
    }

    public String getError(){
        return getSTMGetAccountByCardNoResult().getString().get(2);
    }

    public String getAccountNo(){
        return getSTMGetAccountByCardNoResult().getString().get(3);
    }

    public String getUserCode(){
        return getSTMGetAccountByCardNoResult().getString().get(4);
    }

    public String getCardName(){
        return getSTMGetAccountByCardNoResult().getString().get(5);
    }
}
