//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.08 at 01:42:57 PM NOVT 
//


package vn.unicloud.vietqr.soap.inetservice.model;

import lombok.ToString;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="STM_WithDrawal_RevResult" type="{http://tempuri.org/}ArrayOfString" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stmWithDrawalRevResult"
})
@XmlRootElement(name = "STM_WithDrawal_RevResponse")
@ToString
public class STMWithDrawalRevResponse {

    @XmlElement(name = "STM_WithDrawal_RevResult")
    protected ArrayOfString stmWithDrawalRevResult;

    /**
     * Gets the value of the stmWithDrawalRevResult property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfString }
     *     
     */
    public ArrayOfString getSTMWithDrawalRevResult() {
        return stmWithDrawalRevResult;
    }

    /**
     * Sets the value of the stmWithDrawalRevResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfString }
     *     
     */
    public void setSTMWithDrawalRevResult(ArrayOfString value) {
        this.stmWithDrawalRevResult = value;
    }

    public boolean isSuccess(){
        return getSTMWithDrawalRevResult().getString().get(0).equals("00");
    }
    public String getDescription(){
        return getSTMWithDrawalRevResult().getString().get(1);
    }
}
