//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.08 at 01:42:57 PM NOVT 
//


package vn.unicloud.vietqr.soap.inetservice.model;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fromAcctNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fromRtxnNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toAcctNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inCostAcctNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tranAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="costAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ngaygd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rtxnDescText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="chargeType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fromAcctNbr",
    "fromRtxnNbr",
    "toAcctNbr",
    "inCostAcctNbr",
    "tranAmount",
    "costAmount",
    "ngaygd",
    "rtxnDescText",
    "chargeType"
})
@XmlRootElement(name = "TransferOnline")
public class TransferOnline {

    protected String fromAcctNbr;
    protected String fromRtxnNbr;
    protected String toAcctNbr;
    protected String inCostAcctNbr;
    @XmlElement(required = true)
    protected BigDecimal tranAmount;
    @XmlElement(required = true)
    protected BigDecimal costAmount;
    protected String ngaygd;
    protected String rtxnDescText;
    protected String chargeType;

    /**
     * Gets the value of the fromAcctNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromAcctNbr() {
        return fromAcctNbr;
    }

    /**
     * Sets the value of the fromAcctNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromAcctNbr(String value) {
        this.fromAcctNbr = value;
    }

    /**
     * Gets the value of the fromRtxnNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromRtxnNbr() {
        return fromRtxnNbr;
    }

    /**
     * Sets the value of the fromRtxnNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromRtxnNbr(String value) {
        this.fromRtxnNbr = value;
    }

    /**
     * Gets the value of the toAcctNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToAcctNbr() {
        return toAcctNbr;
    }

    /**
     * Sets the value of the toAcctNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToAcctNbr(String value) {
        this.toAcctNbr = value;
    }

    /**
     * Gets the value of the inCostAcctNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInCostAcctNbr() {
        return inCostAcctNbr;
    }

    /**
     * Sets the value of the inCostAcctNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInCostAcctNbr(String value) {
        this.inCostAcctNbr = value;
    }

    /**
     * Gets the value of the tranAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTranAmount() {
        return tranAmount;
    }

    /**
     * Sets the value of the tranAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTranAmount(BigDecimal value) {
        this.tranAmount = value;
    }

    /**
     * Gets the value of the costAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCostAmount() {
        return costAmount;
    }

    /**
     * Sets the value of the costAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCostAmount(BigDecimal value) {
        this.costAmount = value;
    }

    /**
     * Gets the value of the ngaygd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNgaygd() {
        return ngaygd;
    }

    /**
     * Sets the value of the ngaygd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNgaygd(String value) {
        this.ngaygd = value;
    }

    /**
     * Gets the value of the rtxnDescText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtxnDescText() {
        return rtxnDescText;
    }

    /**
     * Sets the value of the rtxnDescText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtxnDescText(String value) {
        this.rtxnDescText = value;
    }

    /**
     * Gets the value of the chargeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeType() {
        return chargeType;
    }

    /**
     * Sets the value of the chargeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeType(String value) {
        this.chargeType = value;
    }

}
