//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.08 at 01:42:57 PM NOVT 
//


package vn.unicloud.vietqr.soap.inetservice.model;

import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fromAcctNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fromRtxnNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toAcctNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inCostAcctNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tranAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="costAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ngaygd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rtxnDescText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="chargeType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="in_tronghtyn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="in_payto_nn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="in_cmnd_nn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="in_teldc_nn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="soTK" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="in_shnh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="in_internaldesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="in_nguoigui" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="in_cmnd_ng" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="in_teldc_ng" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fromAcctNbr",
    "fromRtxnNbr",
    "toAcctNbr",
    "inCostAcctNbr",
    "tranAmount",
    "costAmount",
    "ngaygd",
    "rtxnDescText",
    "chargeType",
    "inTronghtyn",
    "inPaytoNn",
    "inCmndNn",
    "inTeldcNn",
    "soTK",
    "inShnh",
    "inInternaldesc",
    "inNguoigui",
    "inCmndNg",
    "inTeldcNg"
})
@XmlRootElement(name = "TransferOnline_IDCard")
public class TransferOnlineIDCard {

    protected String fromAcctNbr;
    protected String fromRtxnNbr;
    protected String toAcctNbr;
    protected String inCostAcctNbr;
    @XmlElement(required = true)
    protected BigDecimal tranAmount;
    @XmlElement(required = true)
    protected BigDecimal costAmount;
    protected String ngaygd;
    protected String rtxnDescText;
    protected String chargeType;
    @XmlElement(name = "in_tronghtyn")
    protected String inTronghtyn;
    @XmlElement(name = "in_payto_nn")
    protected String inPaytoNn;
    @XmlElement(name = "in_cmnd_nn")
    protected String inCmndNn;
    @XmlElement(name = "in_teldc_nn")
    protected String inTeldcNn;
    protected String soTK;
    @XmlElement(name = "in_shnh")
    protected String inShnh;
    @XmlElement(name = "in_internaldesc")
    protected String inInternaldesc;
    @XmlElement(name = "in_nguoigui")
    protected String inNguoigui;
    @XmlElement(name = "in_cmnd_ng")
    protected String inCmndNg;
    @XmlElement(name = "in_teldc_ng")
    protected String inTeldcNg;

    /**
     * Gets the value of the fromAcctNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromAcctNbr() {
        return fromAcctNbr;
    }

    /**
     * Sets the value of the fromAcctNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromAcctNbr(String value) {
        this.fromAcctNbr = value;
    }

    /**
     * Gets the value of the fromRtxnNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromRtxnNbr() {
        return fromRtxnNbr;
    }

    /**
     * Sets the value of the fromRtxnNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromRtxnNbr(String value) {
        this.fromRtxnNbr = value;
    }

    /**
     * Gets the value of the toAcctNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToAcctNbr() {
        return toAcctNbr;
    }

    /**
     * Sets the value of the toAcctNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToAcctNbr(String value) {
        this.toAcctNbr = value;
    }

    /**
     * Gets the value of the inCostAcctNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInCostAcctNbr() {
        return inCostAcctNbr;
    }

    /**
     * Sets the value of the inCostAcctNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInCostAcctNbr(String value) {
        this.inCostAcctNbr = value;
    }

    /**
     * Gets the value of the tranAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTranAmount() {
        return tranAmount;
    }

    /**
     * Sets the value of the tranAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTranAmount(BigDecimal value) {
        this.tranAmount = value;
    }

    /**
     * Gets the value of the costAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCostAmount() {
        return costAmount;
    }

    /**
     * Sets the value of the costAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCostAmount(BigDecimal value) {
        this.costAmount = value;
    }

    /**
     * Gets the value of the ngaygd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNgaygd() {
        return ngaygd;
    }

    /**
     * Sets the value of the ngaygd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNgaygd(String value) {
        this.ngaygd = value;
    }

    /**
     * Gets the value of the rtxnDescText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtxnDescText() {
        return rtxnDescText;
    }

    /**
     * Sets the value of the rtxnDescText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtxnDescText(String value) {
        this.rtxnDescText = value;
    }

    /**
     * Gets the value of the chargeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeType() {
        return chargeType;
    }

    /**
     * Sets the value of the chargeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeType(String value) {
        this.chargeType = value;
    }

    /**
     * Gets the value of the inTronghtyn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInTronghtyn() {
        return inTronghtyn;
    }

    /**
     * Sets the value of the inTronghtyn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInTronghtyn(String value) {
        this.inTronghtyn = value;
    }

    /**
     * Gets the value of the inPaytoNn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInPaytoNn() {
        return inPaytoNn;
    }

    /**
     * Sets the value of the inPaytoNn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInPaytoNn(String value) {
        this.inPaytoNn = value;
    }

    /**
     * Gets the value of the inCmndNn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInCmndNn() {
        return inCmndNn;
    }

    /**
     * Sets the value of the inCmndNn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInCmndNn(String value) {
        this.inCmndNn = value;
    }

    /**
     * Gets the value of the inTeldcNn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInTeldcNn() {
        return inTeldcNn;
    }

    /**
     * Sets the value of the inTeldcNn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInTeldcNn(String value) {
        this.inTeldcNn = value;
    }

    /**
     * Gets the value of the soTK property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoTK() {
        return soTK;
    }

    /**
     * Sets the value of the soTK property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoTK(String value) {
        this.soTK = value;
    }

    /**
     * Gets the value of the inShnh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInShnh() {
        return inShnh;
    }

    /**
     * Sets the value of the inShnh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInShnh(String value) {
        this.inShnh = value;
    }

    /**
     * Gets the value of the inInternaldesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInInternaldesc() {
        return inInternaldesc;
    }

    /**
     * Sets the value of the inInternaldesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInInternaldesc(String value) {
        this.inInternaldesc = value;
    }

    /**
     * Gets the value of the inNguoigui property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInNguoigui() {
        return inNguoigui;
    }

    /**
     * Sets the value of the inNguoigui property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInNguoigui(String value) {
        this.inNguoigui = value;
    }

    /**
     * Gets the value of the inCmndNg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInCmndNg() {
        return inCmndNg;
    }

    /**
     * Sets the value of the inCmndNg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInCmndNg(String value) {
        this.inCmndNg = value;
    }

    /**
     * Gets the value of the inTeldcNg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInTeldcNg() {
        return inTeldcNg;
    }

    /**
     * Sets the value of the inTeldcNg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInTeldcNg(String value) {
        this.inTeldcNg = value;
    }

}
